### ISSUE TITLE
choice of license 

### ISSUE THREAD

**Issue by mjkkirschner** [erfajo/OrchidForDynamo#1]
Hi @erfajo 
first:
IANAL ;)

The choice of this license for this repo would make **me** hesitate to use it for any commercial work because of this bit:
``` , which include larger works using a licensed work, under the same license. ``` because I interpret this to mean that any dynamo graph which uses this package must be also open source. Just curious if this is your intention, if so thats cool :).

**Comment by erfajo** [comment]
I would prefer it this way, but I am not sure that I can hold such a position if it should end in a courtroom :-)

What my aim is, is that the essence of my nodes that I share must always be open source. That goes for the code and the node.

But after some pointless discussion at dynamobim forum did my enthusiasm dye, and I pulled major parts away from the public here at Github. I have a kind of lost my willingness to share and participate.

I don’t know if you saw my code before I removed major parts of it? I had shared my own python interpreter, and I had planned to upload my python 3.6 interpreters also. But that was before I ran into the troubles I felt I had to face in the community and the problems getting in touch/in sync with the Dynamo team in general.

Now I just do whatever I feel is right for me and my students, and the people I know from the community :-)

**Comment by erfajo** [comment]
I have changed the license to CC BY-ND 4.0
https://creativecommons.org/licenses/by-nd/4.0/
Essentially saying... you cannot have the source code but you can freely use the package as it is.

**Comment by mjkkirschner** [comment]
@erfajo thanks for considering this! 👍

**Comment by erfajo** [comment]
It was not that easy to understand all those licenses used widely at GitHub and elsewhere. I don't think that many have considered deeply over which license they use.

However, I took the time to read about it and figured that all those open source licenses (GPL-3 and MIT) really meant that the source code should be accessible. That was not my intention at all.
I left using custom nodes since I begun to register that other package authors simply copied my code removing my credentials. So I moved to serialized nodes instead where my code is (better) protected.

If I could be sure that others would respect the requirements for open source, then I would have no problem sharing. If someone could use my code as an inspiration then no problem.
I myself do also use others code to become better, as an example do I use “TheBuildingCoder” as my primary resource (and StackOverflow/Autodesk dev forum). I do also observe how things are coded at the dynamo GitHub site. Not that I totally agree with how the dynamo stuff is done and that is why I make my own nodes where the dynamo OOTB nodes don’t work satisfying for me, especially where they fail to do the job.
But having others to simply steal my code is killing me.

So I figured that Creative Commons licenses were better suited for me. That would grant the users of my nodes/package that I will release it as free software. Thanks to your heads up I also wanted to acknowledge “commercial” interests, so it ended up as the CC BY-ND 4.0 license.
