### ISSUE TITLE
Adding prefix for node name

### ISSUE THREAD

**Issue by Lionel-Lim** [erfajo/OrchidForDynamo#107]
### Is your feature request related to a problem? 

I personally like to use code block to make graph in order to make it shorter and clearer.
However, in code block, i sometimes get this kind of message

`Warning: Multiple definitions for 'List' are found as DSCore.List, List, Orchid.Common.List`

I think it happened because of name collision between Orchid package nodes and OOTB nodes (or category name).
Of course, I can simply put "DSCore" in front of my script but I have done so many things with Code block. So it is quite time consuming job.

### Describe the solution you'd like 

I have never made the package so I don't have deep knowledge of it.
But If you put a prefix for your package, I feel the issue will be clear.

For instance, Orchid.List

**Comment by erfajo** [comment]
This is exactly how it works... this is how all "zero-touch" packages work. 
Since I have +600 nodes, and many of my functions have named convergence with Dynamo, you will meet a demand for adding the full namespace.
In the sample collection is there some examples of how to do it. ex. <a href="Samples/Dynamo_2.x.x/Core/Core-Scripting.dyn>Core-Scripting</a>
