### ISSUE TITLE
Install appears to have failed

### ISSUE THREAD

**Issue by DynamoGuy** [erfajo/OrchidForDynamo#109]
### Operating system
Windows 10, etc

### Revit and Dynamo version

Revit: 2020.1
Dynamo Core: 2.2.1.5175
Dynamo Revit: 2.2.1.5291
Orchid: 2.0 and 2.3

### What did you do? 
Recently got a new work PC, re-installed Dynamo packages on new machine.  Tried to install Orchid via the Dynamo Package window, then remembered that Orchid uses a downloader.  Installed Orchid 2.0 via the downloaded exe.  (Revit was closed.)

### What did you expect to see?
Orchid nodes in the Node menu.

### What did you see instead?
No Orchid Nodes in the Node menu.

I tired installing Orchid 2.3 but this had no effect.

I exited out of Revit and Dynamo fully before attempting the install. 

Any help would be appreciated!  I have a graph that uses List.Sort.Natural that won't work anymore.  It's putting me in a bind with a project.  

Thanks!

**Comment by erfajo** [comment]
The reason is that you dont use the newest version of Revit. When installing Revit 2020.2 you will get Dynamo 2.3. You have dynamo 2.2 and therefore is the search path not 2.3 where I install (230 = 2.3)
You can manually move the orchid folder til the proper path or add another path to dynamo searching for packages, or install Revit 2020.2

**Comment by DynamoGuy** [comment]
That worked!  I didn't realize my new machine was running an old version of Revit.  I'm sure you've answered this same question many times.  Thank you!

**Comment by erfajo** [comment]
No, It is not the first time I got this question. Last night was I doing the last test for a new incremental release, the 7711 build is now available.
