### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by waracana** [erfajo/OrchidForDynamo#115]
Hi, I have tried both the executable file and the manual method, I have also checked settings/paths, etc, it seems like Dynamo can locate the dll files in the bin folder..but I get this warning when I go to Notifications, show details:

"A package called Orchid found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\Orchid could not be verified to have signed dll files.  A dll file was not found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\Orchid\bin\Orchid.dll. No certificate was able to be verified.  Ignoring it."

I appreciate your help with this, I have several scripts that depend on nodes from your package, right now I am stuck at Revit 2019 until I can install Orchid at Revit 2021. Thank you

![image](https://user-images.githubusercontent.com/45979970/118065633-4840a200-b36b-11eb-9a4b-4df48e5ab93d.png)

Update, I am using Revit 2021 and Dynamo Revit 2.6.1.8850:
![image](https://user-images.githubusercontent.com/45979970/118066229-53480200-b36c-11eb-91cf-caf30d0a3f95.png)
thanks

**Comment by erfajo** [comment]
can you confirm that this folder exists?
C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\Orchid

**Comment by erfajo** [comment]
I have checked if the default locations should have changed... I don't look like that has happened.
https://primer.dynamobim.org/11_Packages/11-1_Introduction.html
![image](https://user-images.githubusercontent.com/2844374/118115911-d9eef480-b3e9-11eb-9962-9895b9ac5b54.png)

However, it could be nice if I could check for the proper install path, meaning could you please do a screenshot from your "Manage Node and Package Paths" 
![Snap001277](https://user-images.githubusercontent.com/2844374/118116625-c6905900-b3ea-11eb-88df-c1aa9c8da3f3.png)

**Comment by waracana** [comment]
Hi good morning, thanks for getting back to me and apologies for the lack of response, different time here, probably.

This is where the executable installer placed Orchid when first installed:
![image](https://user-images.githubusercontent.com/45979970/118133302-ac488200-b3ce-11eb-9d6f-fe11343e20b5.png)
There are only 4 files in there.

However, when I open Dynamo I can see this in my add-ons section:
![image](https://user-images.githubusercontent.com/45979970/118133608-08130b00-b3cf-11eb-97a5-2e7279f8fa0e.png)
Except for Clockwork, it seems that these packages are installing here by default as of Revit 2021:
so I tested the manual install placing Orchid there as well:
![image](https://user-images.githubusercontent.com/45979970/118133857-4a3c4c80-b3cf-11eb-84e4-68b5c7c0e262.png)
but it still doesn't load the libraries in Dynamo, however, when I compare the contents of the zipped version of Orchid, I can see what seems to be the complete collection of files in the bin folder:

![image](https://user-images.githubusercontent.com/45979970/118134155-98e9e680-b3cf-11eb-96cb-9058cba16974.png)
when I compare the contents of the 2 folders, i notice that the 4 files that they have in common:
![image](https://user-images.githubusercontent.com/45979970/118134439-ee25f800-b3cf-11eb-9da6-a77fcb48a0d3.png)
seem different, the ones at RVT 2021\Dynamo\2.6\packages have a "lB" in their name

This is how my "Manage Nodes and Package Paths" looks like:

![image](https://user-images.githubusercontent.com/45979970/118134801-51b02580-b3d0-11eb-88a4-75b960d31baa.png)

I believe I tried this last night, but I will try to copy all the contents from the RVT 2021\Dynamo\2.6\packages folder into the other destination and see what happens, if it doesn't work I'll uninstall and repeat the copy paste.

Thanks for your help

**Comment by waracana** [comment]
Update:
After copying the contents to \AppData\Roaming\Dynamo\Dynamo Revit\2.6\packages\Orchid\bin it seems Orchid now loads all nodes, but I get this warning now:

![image](https://user-images.githubusercontent.com/45979970/118136487-2a5a5800-b3d2-11eb-9910-d3575ca6453c.png)
I feel like I should ignore it, should I eliminate the contents of the other folder?
C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages
and eliminate the path in "Manage Nodes and Package Paths" just in case this is what is confusing Dynamo?

Thanks

**Comment by erfajo** [comment]
I think I know what you have done...
you have not read the text on the download page inside the package manage download site. It said that you should download Orchid from Github. Nevertheless, you installed the package, and then did you use the one node "Readme" which opened the Github page. At some point did download the "real" installer and installed Orchid. After tweaking the folder issue you now have the full package... but the first readme node in the "placeholder" package might now be a "dead" node, that's why you now get an error on the node.

At some point I might have moved the readme node, in the "real" package, and have not updated the "placeholder" package... and I don't suppose I will update it since it is only a placeholder!

However, I have now made a new installer that opens the file where package paths are written, and the installer will now use the first path given as its installing path. By doing this I have now also solved the challenge for all companies who are installing on a network drive, as long as the first path is the one with the network drive. 
This seems also to be how the package manager is installing packages nowadays.

This will be rolled out next time I update Orchid.

By the way, only the two top paths should be left in your "Manage Nodes and Package Paths", remove the others.

**Comment by waracana** [comment]
Hi, I did read the text, I may have not done everything correctly but I read it, first thing I did was searching for the Orchid package through the Dynamo manager, then I installed it and just got the Read Me node, as usual (I did this whole procedure in Revit 2019 without problems).

When you run the scrip, that's when the Readme node develops and you can see all the instructions in the watch node.

I went to Github, chose the appropriate version of the installer (Revit 2021 / Dynamo 2.6), downloaded and installed it, noticing that it sort of entered a loop, when it was done installing it would pop up again until I would cancel the install, but this only happened the first time I installed the package.

Then I started investigating and eventually uninstalled to try the whole procedure again, this time running the installer as Administrator, just in case, and it didn't enter a loop, but still, Dynamo didn't load the Orchid library. Only then I tried the manual method, and I read the other posts in Github related to this issue and took into account your answers about paths, etc.

Right now the nodes are loading well, if I notice anything strange I will uninstall and use your new installer.
I appreciate your time and help, and above all, great work with the package, it is incredibly useful.

I have noticed that, for some reason, when Orchid is installed, there is a node by Clockwork that just stops working, that's why this whole thing begun in the first place, I wanted to test if that also happened with a different version of Dynamo / Revit, it's a node called Character.FromNumber, 
![image](https://user-images.githubusercontent.com/45979970/118159041-8df07f80-b3ea-11eb-8c97-c5baf4dd28fe.png)

once I open it for edition I can see this warning:
![image](https://user-images.githubusercontent.com/45979970/118159128-a52f6d00-b3ea-11eb-8c9c-383926745a52.png)
seems like there is something happening with a definition for Math, but this error happens only when Orchid is installed, sorry if this is completely off topic, please ignore me.

I will eliminate the conflicting paths from the settings dialogue, thanks for all your help.

Best regards

**Comment by erfajo** [comment]
first, as written in capital letter, you should not install from the package manager... however, those who do that will get only two nodes as you did... and if they don't figure to use the readme node, then will they never realize that they should have went straight to the Github page.
![image](https://user-images.githubusercontent.com/2844374/118162698-5650fa00-b421-11eb-9d08-e8dbbbbccd11.png)

next, your Clockwork error...
This kind of errors will happen due to the missing namespace used in the Clockwork node. The call should be DSCore.Math.Floor as written in the error message.
Since the dynamoteam has 600 functions and I have 700, then will we share functions like the math class. In such cases must the function be provided with the full namespace.

lastly, I expect that I am one of the very few who handles the new units in Revit for all versions of Revit. I will expect all packages are either not ready for Revit 2022 or they will not work for Revit 2020 anymore. Only Revit 2021 has both the old and the new unit system. This could be a problem in many company settings where several Revit versions exist, packages might fail in all those cases.

Since the initial issue is solved I will close this issue

**Comment by waracana** [comment]
Thank you, I apologize, I thought I had read everything, it's clear I hadn't, I'll pay attention next time.

![image](https://user-images.githubusercontent.com/45979970/118164914-a617cd00-b3f1-11eb-9c89-b181e0bd33f6.png)
Thanks again for the clockwork error, you also sorted that one, I appreciate!
