### ISSUE TITLE
No Revit nodes in 200.4.0.7824

### ISSUE THREAD

**Issue by DynaBimm** [erfajo/OrchidForDynamo#118]
Hello, Erik!

Tried with Win10 and Win8. 
Thanks!

**Comment by erfajo** [comment]
https://github.com/erfajo/OrchidForDynamo/blob/master/error.md

**Comment by DynaBimm** [comment]
> ...and you have read this!?

@erfajo , yes! 
200.3.0.7767 works fine.

**Comment by erfajo** [comment]
Could you please try to take a screenshot of the bin folder where Orchid is installed
C:\Users\ [user] \AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\Orchid\bin
![image](https://user-images.githubusercontent.com/2844374/121015913-d279fb80-c79b-11eb-9243-03207521f633.png)

**Comment by DynaBimm** [comment]
@erfajo,
![image](https://user-images.githubusercontent.com/62960555/121031053-b2a20200-c7b2-11eb-82ef-539bbe2e0418.png)

**Comment by DynaBimm** [comment]
@erfajo , copied Orchid folder to Dynamo from other Win 10 PC. It's working!

![image](https://user-images.githubusercontent.com/62960555/121033162-9b641400-c7b4-11eb-9eba-607ad1429efc.png)
25 items total

**Comment by erfajo** [comment]
what I dont get is how you got the "core" assemblies installed!?
all files named OrchidCx is only for the sandbox version, while OrchidRx is for the Revit version.
did you install this manually and some how didnt get that you got two versions of Orchid!?

**Comment by DynaBimm** [comment]
@erfajo , 
no, just used exe to install. Even tried to delete Orchid folder before install.

**Comment by erfajo** [comment]
hmmm... strange, 
At some point someone has had to add the "Sandbox" version to the computer you are using, since I never have included this in the executable. I only include the Revit version as is the case with Dynamo. It is also only the Revit version which is shipped with Revit, you need to do an extra effort to get the sandbox version!?
however, problem is solved and I will close the issue :-)
