### ISSUE TITLE
Purge

### ISSUE THREAD

**Issue by MarkAckerley** [erfajo/OrchidForDynamo#12]
Hi Eric,

Thank you so much for this node it is awesome to have this functionality :)

I presume it just needs a while loop adjusting...

Cheers,

Mark

### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2018.3.1
Dynamo: 1.3.2 & 2.1.0
Orchid: 05.11.2018

### What did you do? 
Purge active document

### What did you expect to see?
Number of items checked reduced from 568 to 0

### What did you see instead?
Number of items checked returned 384

![image](https://user-images.githubusercontent.com/41670424/47987660-fce11500-e0d7-11e8-97b7-a3e75ae1b513.png)
![image](https://user-images.githubusercontent.com/41670424/47987622-e470fa80-e0d7-11e8-843b-2afb37c02d16.png)
![image](https://user-images.githubusercontent.com/41670424/47987595-d28f5780-e0d7-11e8-8ba1-e180fdd291bf.png)
![image](https://user-images.githubusercontent.com/41670424/47987643-f05cbc80-e0d7-11e8-9b65-6dd9d23cf310.png)

**Comment by erfajo** [comment]
I know that it by now only can purge families and that kind, it cannot purge materials and material assets yet.
I use the Performance Advisor to purge, and I dont have an overview yet over all the rules, I have found these but are working on a full solution.

https://spiderinnet.typepad.com/blog/2012/04/revit-api-2012-native-revit-performance-advisor-rules.html

However, the Performance Advisor is not bound to run only on the current document, therefore is it a better solution to use this.

**Comment by erfajo** [comment]
Hi Mark,

Could you please test the updated Purge node again?

It has been an extremely complicated function or set of functions I needed to code for solving all the issues to reflect upon when purging.

If you could give me some feedback would it be good. I have thought over many issues myself, but I can surely have overlooked some.

My purge node is more efficient than the built-in purge command and to my knowledge has no one before I build such a comprehensive solution taken so many issues into consideration.

I had in advance control over purging all relevant elements, what was difficult was to purge materials and assets since they are connected in another way than elements to the document.

I have tried to keep materials bound to all kind of elements and views but not materials bound beyond that. That includes materials in all kind of stair, railing, topography, mep and structural elements.

All assets are also evaluated and purged if they are floating in the document not connected to any material.

On the other hand, can it purge elements, materials, and assets which are set by the Revit “system” but never used.

Newest build is 6896 for both versions.

**Comment by MarkAckerley** [comment]
Hi Erik,

With pleasure, looks good to me!

[PurgedTestFiles.zip](https://github.com/erfajo/OrchidForDynamo/files/2594507/PurgedTestFiles.zip)

Thanks again,

Mark

**Comment by erfajo** [comment]
Thanks for your feedback :-)

**Comment by erfajo** [comment]
Hi again Mark,

I had to change the node behavior for the time being. I have added a bool value for including purging materials and assets. I have included this text to the node.

_Purge document. Set "completely" to true for including materials/assets!
Please note "completely" purges also materials and materials assets that are used in "peripheral" elements and settings. Among this is included materials/assets bound to imported model elements, and materials/assets in settings like "Site" etc._

![capture](https://user-images.githubusercontent.com/2844374/48766232-4757b980-ecb4-11e8-8690-dc31c0b9266e.png)
Please update to build 6898 for further testing concerning purge.

**Comment by MarkAckerley** [comment]
Thanks Erik, 

This is so useful for us BIM managers, would you mind if I tweeted to spread the word?

Mark

**Comment by erfajo** [comment]
that is fine for me :-)
I am working on getting those imported elements... but it is searching for the needle in the haystack, since no one has done this before me. I have checked that Jeremy Tammik don't have an answer, so I consider to write him when I reach the goal :-)

**Comment by erfajo** [comment]
I have just released a purge node using PostCommand, however, it has all the well-known limitations but guarantees that purging is done as it is known inside Revit.

_Purge document by Post Command.
Post commands can only take the current document to be run once. Re-run the graph to re-activate the post command. To get back the "Purge" window inside Revit, set the "activate" value to "false" and re-run the graph once more!_

![capture](https://user-images.githubusercontent.com/2844374/48782516-a7fbec00-ecde-11e8-8e6c-0c353cffbec6.png)

**Comment by Hecheva** [comment]
Hello @erfajo 
Just found this post by chance.
As you mention the Building coder talks about the "PostCommand" or "Advisor" methods. The postcommand method is not good for several documents and the Advisor method doesn't purge materials and assets. I've also found this [post by Harry Mattison](https://boostyourbim.wordpress.com/2016/10/21/purge-unused-materials-for-another-rtceur-api-wish/) on how to purge materials.
I was wondering if you could share some guidelines or hints on how you were able to create this purge node.
Regards

**Comment by erfajo** [comment]
How to code a node can be found at the dynamo team github page and dynamobim page. I dont do anything special other than that. I might have some way to do the coding but this is something I have evolved over long time and would include some time to explain, meaning I would include a series of videos or something like that. I am affraid I dont have time for doing that at the moment. However, there are so many other who explain coding from many perspectives, try to look them up.

**Comment by Hecheva** [comment]
Hello @erfajo,
Thank you for the response. I understand that it takes a lot of time to explain this kind of thing but I had to try! :D Fortunately, after some work yesterday, I managed to do a Purge tool with the API.
Kind regards

**Comment by erfajo** [comment]
Sorry for being late, but, are you familiar with my other node for purging? it should do the job you are asking for.
![Purge PostCommand](https://user-images.githubusercontent.com/2844374/142989864-4405e2bd-31b8-4110-869d-447a83fd1261.png)
.

**Comment by Hecheva** [comment]
Hello @erfajo 
Thank you very much for coming back to reply.
I am aware that you have a purge node. But I was asking because I wanted to program a batch cleaner with the API, not with Dynamo.
I finally managed to do what I wanted by using the performance adviser and then collecting all the used materials.
Cheers!

**Comment by erfajo** [comment]
thanks, now I understand.
I read the link you attached, and it seams to be a doable way to do it. 
I do it differently, however, the result should be the same :-)

**Comment by Hecheva** [comment]
I finally didn't do it as Harry Mattison.
If you are curious I made a blog post: https://plbim.blogspot.com/

**Comment by erfajo** [comment]
Thanks, 
I can see that you use looping a lot, I use linq queries. I cant see that you are breaking for an ElementId "runned" once, many of your elementids will be the same, so to make et faster you should filter for that.

something i noticed... you dont check for "paint" materials. Like I assume you use ParameterType.Material in parameters, where I use BuiltInParameter (BuiltInParameter.MATERIAL_ID_PARAM, BuiltInParameter.POCHE_MAT_ID). And where you use "hostAttCollector" I use types collecting (typeof(HostObject), typeof(GenericForm)).

you should also try using "ElementClassFilter" instead of "OfClass" for you FilteredElementCollector.

**Comment by Hecheva** [comment]
Wow!
Thank you very much for that. may ask about your points?

1. Yeah, I know I should use more Linq. I will try to implement it
2. I hadn't thought about filter ElemntIds that I have already checked. How do you suggest doing that? to add already checked elements to a list and then check if every new element is already in that list?
3. I will check for Paint materials, I forgot that as well
4. ParameterType.Material I use this so even user-created material parameters are captured
5. MATERIAL_ID_PARAM: This seems to be applied only to certain elements?
6. POCHE_MAT_ID: Is this for the material that is used when in coarse mode? which elements have this parameter? I can't seem to find an element with this  parameter with RevitLookup
7. What do you mean by types collecting? can you put two classes inside the same collector filter? 
8. What is the benefit of ElementClassFilter vs Ofclass?

**Comment by erfajo** [comment]
ad 2)
I have as you a list where I collect used materials --> materialTemp
            var materialFlatten = materialTemp.Flatten();
            var usedMaterialIds = materialFlatten.Cast<ElementId>().Distinct().ToList();
