### ISSUE TITLE
Family.Family document node missing

### ISSUE THREAD

**Issue by brane1012** [erfajo/OrchidForDynamo#127]
Hi,

few years back I had a Dynamo script (Dynamo version 1.3) where I used Family.FamilyDocument node.

Now I have migrated to newer version and that node appears to be missing.

Any advice?

**Comment by brane1012** [comment]
And same thing with Document.LoadFamily node?!

**Comment by erfajo** [comment]
I know this is a problem, the migration seems to be broken in dynamo 2.x versions, even I still am maintaining it...
`
  <priorNameHint>
    <oldName>Orchid.RevitProject.Elements.Family.FamilyDocument</oldName>
    <newName>Orchid.RevitProject.Elements.Family.EditFamily</newName>
  </priorNameHint>
`
concerning Document.LoadFamily this is still its name!?
Orchid.RevitProject.Common.Document.LoadFamily

**Comment by brane1012** [comment]
Tnx for help.

And what about Parameter.SharedParameters node and Parameter.Parameters node?

**Comment by erfajo** [comment]
That depends... try to browse around, try using search...
However, they will be present in both Orchid.RevitFamily and Orchid.RevitProject!

**Comment by erfajo** [comment]
Hi @Niki-ko 
It is the right place, however, do always make a new issue instead of adding something to other's issues unless it is strictly the same!
This is why I will not answer your question to blur what this issue is about, but I have the answer and it can be found in my sample collection… so set up a new issue or search my samples :-)
