### ISSUE TITLE
Orchid package not showing up in Dynamo

### ISSUE THREAD

**Issue by BenjiTan1** [erfajo/OrchidForDynamo#130]
Hello Erfajo,

I am currently struggling to install Orchid package, I followed all your instructions, tried to install it manually etc but in vain. So I'm asking for your help.

I'm using Revit 2019 and I installed Dynamo 2.0.0 (at first I had Dynamo 1.3.4, I thought it was compatibility issue tho). All the files are in the Packages file but it just doesnt appear in Dynamo !

![image](https://user-images.githubusercontent.com/74857196/134485349-92b146b7-1eee-433d-905d-07b001c62f6c.png)
![image](https://user-images.githubusercontent.com/74857196/134485490-cae5b647-b5b8-4578-8fe3-a29a382772b9.png)
![image](https://user-images.githubusercontent.com/74857196/134485574-8bdde29a-3f21-4638-8343-1d52dea94cd5.png)

Any idea on how I can solve this issue ?

Thanks in advance for your help

**Comment by erfajo** [comment]
Check you paths if they are set correct according to where you have installed Orchid, inside dynamo.

**Comment by textilesense** [comment]
Good morning @erfajo . Got a similar issue to BenjiTan1's, but think that Orchid's node don't show as I am working on a Revit 2022 release with a 2.10 Dynamo build, whereas apparently Orchid works with a Dynamo 2.12 build for Revit 2022. Hence, my understanding is that the only way I have to update my Dynamo build is to update the Revit build I am working on to 2022.1.2 or so, but I have fear that in this case Dynamo would automatically update to the 2.13 build (the very latest one currently available), which probably would not work for the latest Orchid release (good for Dynamo 2.12, as mentioned). Do I have any chance to access Orchid then? Thank you very much, sorry for this lengthy message.

**Comment by erfajo** [comment]
Dynamo always makes a folder according to the version. This path was rather easy to read before the 2.10 version, now it's more problematic. That's why I had to do it the way it used to be ... namely to point to the version as a folder. The 2.10 version will be found in a 2.10 folder, and 2.12 will be found in a 2.12 folder ... which means that since you have not updated your Revit 2022 version, you will need to find the path where your packages are stored , and see if there is not a parallel 2.12 directory, then either add this 2.12 directory to your search path or modify the contents of your 2.10 directory.

**Comment by textilesense** [comment]
Much appreciated, thank you!!

Il mer 29 dic 2021 11:20 The Orchid Project ***@***.***> ha
scritto:

**Comment by textilesense** [comment]
Do you mean something like what shows in the following screengrab?
[image: Diretory Orchid Dynamo 2.10.JPG]

Il giorno mer 29 dic 2021 alle ore 11:20 The Orchid Project <
***@***.***> ha scritto:

**Comment by erfajo** [comment]
?

**Comment by textilesense** [comment]
As you can see in the screengrab, my Packages folder (containing the Orchid
folder) is located in the 2.10 folder (with the latter being located in the
Dynamo Revit folder), with no evidence of any 2.12 folder ("you will need
to find the path where your packages are stored , and see if there is not a
parallel 2.12 directory, then either add this 2.12 directory to your search
path or modify the contents of your 2.10 directory"). Is this the reason
why Orchid is not working, as there is no 2.12 folder? (sorry, I might seem
a total idiot, but I am new to those topics)

Il giorno mer 29 dic 2021 alle ore 17:12 The Orchid Project <
***@***.***> ha scritto:

**Comment by erfajo** [comment]
I cant see anything, nothing is attached!? However, please download the zipped version and move the Orchid folder and its content into your dynamo package directory.
looking something like this
![image](https://user-images.githubusercontent.com/2844374/147685128-8de04a03-da6d-45aa-89e5-2359a1cd4eda.png)

**Comment by textilesense** [comment]
Apologies, please see the attached image: it seems to me that it shows
exactly the same thing shown in your screengrab, with the difference that I
have a 2.10 folder (consistent with the Dynamo version I am using) instead
of a 2.12 folder

Il giorno mer 29 dic 2021 alle ore 17:48 The Orchid Project <
***@***.***> ha scritto:

**Comment by erfajo** [comment]
then it should work...
have you tried all the other error options described on my error page?
Does it still not work if you move all other packages out? if so then I cant help you since I dont have the Revit 2022 without update 1 installed anywhere. Meaning I cant test it. However, I do not think that should be the problem, it is more likely that some other package you have installed comes with the dynamo assemblies and that is not allowed!

**Comment by textilesense** [comment]
are you suggesting to move Archilab, Clockwork, Monocle, Rhythm and Spring
nodes folders (not Dynamo text), as per the attached, back to the 2.10
folder and leave in the packages folder only Orchid? Sorry again for my
dummy approach, but really need assistance... What I am struggling with is
to add Shared Parameters to a family taking them out of an Excel file,
which is extremely easy to do with the AddSharedParameters node within  the
Orchid Package, whereas it seems to be quite more complicated with the OOTB
nodes like CreateSharedParameters.
Gratefully.

Il giorno mer 29 dic 2021 alle ore 18:01 The Orchid Project <
***@***.***> ha scritto:

**Comment by erfajo** [comment]
As it says on my error page... anything but Orchid, and then move the other packages back one by one until you find the bug. You must restart Revit for each package you move, and you have to start dynamo every time... then you will find the package that courses the problem. If it is Orchid which is the problem, I cant help you.
and please test all paths you have in dynamo, if this is more than the path for 2.1 then test also these paths!

**Comment by textilesense** [comment]
Thank you, I'll try and let you know!

Il giorno mer 29 dic 2021 alle ore 19:03 The Orchid Project <
***@***.***> ha scritto:

**Comment by textilesense** [comment]
Hello there! No fortune so far...
I tried to leave Orchid folder alone in the 2.10 package, having closed
both Revit and Dynamo: no Orchid nodes in Dynamo after opening it
unfortunately.
I have two more "Dynamo build" folders, namely 1.2 and 2.5: their Packages
folders are totally empty.
I assume that simply Orchid doesn't work... that's really bad...

Il giorno mer 29 dic 2021 alle ore 19:03 The Orchid Project <
***@***.***> ha scritto:

**Comment by erfajo** [comment]
The most common mistake is that someone has placed dynamo assemblies in their package, and that Dynamo therefore blocks everything else written for other versions of Dynamo. It is a typical beginner mistake, but which can be incredibly difficult to troubleshoot if you are not experienced. This can usually be ascertained by moving all other packages out so that nothing but Dynamo works, and then moving package by package back... starting with Orchid, because then you know that it works.

But, since it has apparently not worked for you, I do not know what else might be the problem. It is usually not a problem to use older versions of Dynamo, as long as it is within the overall Revit version... which means that Revit 2022 should support Dynamo 2.10 - 2.12, and I assume that 2.13 should also work.

You are the only one who has mentioned that Orchid 2.12 does not work with Revit 2022 (without update 1). BenjiTan1 who created this issue has not responded since September, so I have to assume it works there... by the way, this is another reason to NEVER continue on other users issues, make your own and possibly refer to this issue in your own issue... now this issue has become a mess.

However, if I do not receive other requests for this error, I assume the error is due to something else that has not been seen before. Besides, your error description does not help me, and surely not when it looks like you are not using the github platform for your reporting, but via email on computer or phone.

You may be able to resolve your issue by updating Revit, or using an older version of Revit.

Where as everything is, it unfortunately means I have no options to help you.

**Comment by textilesense** [comment]
I understand. There is no "hidden" reason why I am using e-mail tho, it is
just a beginner improper use.
I warmly thank you for what you do and have so far done for me.
Happy new year!!!

Il ven 31 dic 2021 12:49 The Orchid Project ***@***.***> ha
scritto:

**Comment by erfajo** [comment]
I have just updated the error page...
https://github.com/erfajo/OrchidForDynamo/blob/master/error.md
This includes all the sceneries I have registered as possible errors and solutions.
