### ISSUE TITLE
VirusTotal flagged exe file as malware

### ISSUE THREAD

**Issue by Paunchybird** [erfajo/OrchidForDynamo#145]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 21
Dynamo: 2.6
Orchid: 206

### What did you do? 
I checked for malware in the exe file. VirusTotal and other flagged it as malware. 
![IMG_20220310_123703](https://user-images.githubusercontent.com/46102422/157654287-96855cf2-9e90-40e8-a929-d4ac69b01de0.jpg)

**Comment by erfajo** [comment]
As I can see what Cynet alerts means, this will end as a detected issue. I am asking the installer to clean the old installation before installing the new one.
You can get the commands executed behind the installer by visiting Inno Setup, this is the same installer as dynamo was built with in the old days, I am not sure if they still use Inno Setup

the installer is extremely simple since it only needs to find where dynamo does install its packages. for finding that I read the "DynamoSettings.xml", and read the line where the path is described. Then I copy what I have in the zip file to that location so the user don't need to take care of it.

This is the line of code where it gets the command to delete the old installation
[InstallDelete]
Type: filesandordirs; Name: {code:GetRevitPath}\Orchid

But if you don't trust that, then use the zipped version or don't use Orchid at all.

**Comment by erfajo** [comment]
I close this question as it has no relevance...
