### ISSUE TITLE
Document Families

### ISSUE THREAD

**Issue by MarkAckerley** [erfajo/OrchidForDynamo#146]
Hi Erik,

I hope you are well and I would be very grateful for your assistance.

My intended workflow:

Background open project document
Return all loaded Revit families, in background opened document, from a list of categories
Filter and reload only those families which meet criteria
Close project document

Unfortunately, when I background open with the Orchid node, I cannot run a FilteredElementCollector.

I do not want to load every family from the folder, as there are thousands and I won't know which families are in the project unless I background open? Unless there is some other method of finding out?

I have dug around but cannot find a solution for this, would you have an alternative workflow?

Thank you for your time and efforts,

Kind regards,

Mark

Revit 2020, 
Dynamo 2.3.1

![image](https://user-images.githubusercontent.com/41670424/162438797-ce1f9141-14ba-4e83-b946-8a5ebc817a03.png)

**Comment by erfajo** [comment]
Hi Mark,

No it is correct that you can’t use my documents inside a python node.

I have chosen to do it exactly as the dynamo team does, and for a long time was I kind of angry that they shielded their classes. However, I did the same so that users would have to complain to me, and then would I make them point towards the dynamo team and complain over their behavior.

But years have passed, and I could be the larger man compared to them, and “release” all my classes so users could get the wrapped content and use it in their own nodes.

This means I will have to do some refactoring in my code before I can release it again. What is your deadline for this?

**Comment by MarkAckerley** [comment]
Hi Erik,

Thanks for getting back to me, I've used Rhythm nodes to do the same task, so no urgency.

I hope you have a good weekend,

Mark

**Comment by erfajo** [comment]
If you think using Rhythm nodes is better, then I will not do more about it this time.
