### ISSUE TITLE
Create Shared Parameter in Family Document - Orchid - wrong parameter type

### ISSUE THREAD

**Issue by oliwerkulpa** [erfajo/OrchidForDynamo#153]
Hello,

I’ve created a script in the past to create Shared Parameters in Family Document by Excel data using Orchid Package. I wanted to reuse that in Revit 2022/Dynamo 2.12 but with no luck. I really want to use that workflow since that node lets me add tooltips. I’ve already tried with one changing lacing, creating only one parameter.
Am I missing different input of Parameter Type input?

![image](https://user-images.githubusercontent.com/55832232/170506058-e0b2ca46-f4e1-4097-8118-90398def705b.png)

Many thanks in advance,
Oliwer

**Comment by oliwerkulpa** [comment]
Much appreciated! And - yeah. Graphs sound better. I must’ve missed that change.

**Comment by erfajo** [comment]
@parameter type and unit type
The problem should be solved by now. However, it started a quite comprehensive refactoring and recoding. For the last couple of years has Autodesk been working on changing the entire unit handling inside Revit, but things changed for every version from 2020 until 2022 including some of the update versions as well.
But I admit it looks like it has finally reached a level where nothing new is happening since the 2023 version looks like 2022 concerning unit handling. That is why I decided to code some handling methods which can work with 2020, 2021, and 2022 (and beyond) versions in a more way so it should be able to handle all the differences.

@graph
The ”thing” we create has never been named ”scripts” or ”scripting”, it is a layman's term that never should have been used. I think that it derives from Grasshopper users… where the layman term neither should have been used at any time. 
Both in Dynamo and Grasshopper are it Directed Acyclic Graphs we are creating…
[https://erfajo.blogspot.com/2019/03/graphs.html](https://erfajo.blogspot.com/2019/03/graphs.html)

**Comment by oliwerkulpa** [comment]
@ parameter type and unit type
Once again thank you for addressing this issue, @erfajo. I'm familiar with changes in recent versions of Revit and messing up the unit handling. Let us hope that won't be changed in years to come.

@ graph
Thanks for the link as well. I'll socialize that change in our company. "Script" always reminded me of a cheat code. That term also does not carry the visual part of Dynamo experience, focuses on coding execution.

Huge kudos to you and your hard work!
Best reagards!
Oliwer
