### ISSUE TITLE
Revit 2022 Installation Problems

### ISSUE THREAD

**Issue by tbiddle81** [erfajo/OrchidForDynamo#156]
Revit: 2022
Dynamo: 2.10.1.4002
Orchid: 2.12

I tried the manual method of copying files into the location of my dynamo packages (C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.10\packages), but when I open Revit and Dynamo there is no "Orchid" under my add-ons.  I have searched all over and can not figure this out.  Please help!

**Comment by erfajo** [comment]
and you did copy the content into  folder named "Orchid"? you cant copy it into the root of the folder...
next, have you seen the error page and tried the suggestions there?
last, try to see if you computer is blocking assembly files by default... right click and goto properties to see what is going on.

since you needed to do it manually there must be some restrictions on you computer you must be aware of, you need to find a way around those...

**Comment by BIMRail** [comment]
I @erfajo , I have same problem. with the installation of Orchid 2.12 on Revit 2022.
I have do a manual installation (see the screenshot) and other tests, but i haven't got success.
Dynamo show me this error: "_A package called Orchid found at C:\ProgramData\Autodesk\RVT 
2022\Dynamo\2.10\packages\Orchid could not be verified to have signed dll files. A dll file found at C:\ProgramData\Autodesk\RVT 2022\Dynamo\2.10\packages\Orchid\bin\OrchidRB.dll did not have a signed certificate. Ignoring it_"

How can I resolve?
Thanks.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/95629865/172416247-5899597c-cdde-4bf6-86b4-ca45faec3c60.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/95629865/172416228-5652bcdb-1dfb-4392-8e79-b5816015acf6.png)

**Comment by erfajo** [comment]
It looks like the problem described in the error page. You need to unblock the assembly files. It is correct that my assemblies are not signed.
Next, you should update your Revit version to the latest release. One of the updates will include dynamo 2.12 instead of 2.10
