### ISSUE TITLE
adding shared family parameter with (Family Type) not working

### ISSUE THREAD

**Issue by aymanokail** [erfajo/OrchidForDynamo#177]
finally i got the Orchid package working in my dynamo for Revit.
now it is all working properly except for 1 issue
when i add shared parameter with type "Family Type", it as added but with another type which is "Number" as per the below photos.
so how i can fix this ?

### **Excel Sheet:**
   ![image](https://user-images.githubusercontent.com/64815121/205440967-feecba36-5bac-4391-8d28-5ba3255978b1.png)

### **Screen shot from Revit family after running the dynamo:**
  ![image](https://user-images.githubusercontent.com/64815121/205440990-a5d8c898-021a-4039-a394-694eca486639.png)

**Comment by erfajo** [comment]
The fix is, that you need to do it correctly... if the node gets a condition not suited it falls back to "number", maybe I should let it cast an error instead.

If you want another type to be associated, then see the sample collection for families, FormSetGet.
![FormSetGet](https://user-images.githubusercontent.com/2844374/205876319-d6bf6c71-3156-46f8-b313-6691065f4ce2.png)
