### ISSUE TITLE
Print.CreateSetting (Method not found: 'Double)

### ISSUE THREAD

**Issue by Glenn36** [erfajo/OrchidForDynamo#179]
Hi,

I'm using the node Print.CreateSetting but i get an error while using it in Revit 2023 (Dynamo 2.13)
My script and the node works perfectly in previous revit versions, But now i get the following error. See attached image.

![image](https://user-images.githubusercontent.com/120396009/207077695-633c64af-d150-4580-b904-e0c3946b3fe4.png)

What am i doing wrong?

**Comment by erfajo** [comment]
please add the GRAPH so I can try to test it... however, please do update first to latest version (216) and update your Revit as well to 2023.1

**Comment by Glenn36** [comment]
Hi,

First i updates my revit tot 2023.1 and my dynamo to the latest version. But it didn't resolve the problem.

My graph is kinda long, so i hope this png will clearify some things.
I wanted to upload the dyn file, but it won't let me.

I hope you can help me.
![11_VOL_Batch print GitHub_2022-12-13_02-56-31](https://user-images.githubusercontent.com/120396009/207350437-8a966397-cd54-4b6a-bba4-4bc8f2b88c4d.png)

**Comment by erfajo** [comment]
I dont want to use time for rebuilding your graph, so if you want some help you must give me it so I can walk through it.
add ".txt" to the file so it can be uploaded.
by the way, I cant see anything on the image at all... if I should be able to do that you must zoom into a few nodes and use the camera, otherwise will the resolution be too small for anything.

**Comment by Glenn36** [comment]
I didn't know it was possible to post the graph.

See the attached file:
[11_VOL_Batch print GitHub.txt](https://github.com/erfajo/OrchidForDynamo/files/10227196/11_VOL_Batch.print.GitHub.txt)

**Comment by erfajo** [comment]
I have tried to look at your error message, and it looks like you have not updated Orchid!?
in the file uploaded it also says 204 as the Orchid version, I really do hope that is an error, since that will never go. It should have been at least 213 if you use Revit 2023!
Looking closer to the error message it also mentions "DisplayUnitType", and that was for sure deprecated in Revit 2023 and I do also think that was the case in Revit 2022...

So to be sure... you do have the proper version of Orchid installed that is meant for the correct Revit and Dynamo version!?

**Comment by Glenn36** [comment]
Sorry, my bad. I really thought i had the newest version installed. But somehow it still loaded the old version.

The problem is solved now. Sorry for your time.

**Comment by erfajo** [comment]
That's ok... just to inform you, with the release of Revit 2021 did Autodesk rewrite their unit handling. In Revit 2022 was both unit handling available but from Revit 2023 most of the old deprecated. Even more, over the next couple of years, are going to be deprecated, so it is very important to have the proper combination of Revit, Dynamo, and Orchid installed.
Due to the comprehensive package I code, am I forced to code exactly for every version of the last four versions for Revit, not that it is any problem at all… but that is the scene :-)
