### ISSUE TITLE
Schedule.OnSheet - Node Function Changed between builds

### ISSUE THREAD

**Issue by rookiogmailcom** [erfajo/OrchidForDynamo#196]
### Operating system

Windows 10

### Revit and Dynamo version

Revit: 2023.1.1.24
Dynamo: 2.16.1.6510
Orchid: 216.3.0.5812

### What did you do? 

Opened Graph previously built using Orchid Nodes from 213.2.0.8342

### What did you expect to see?

The Nodes to work in a similar if not identical fashion to the previous version
I would expect if a node function is going to change dramatically that it should get a unique name and ID so that existing graphs are not completely broken.

### What did you see instead?

Nodes function has changed but the name and apparently the ID of the node have not changed?

e.g. Schedule.OnSheet - Node accepted a sheet as input and output a list of schedules on that sheet.
![2023-03-14_16-11-29](https://user-images.githubusercontent.com/90225478/224900987-1dadbd99-eea3-4d46-a3e5-feb349a2c723.png)

After updateing to new build:
Schedule.OnSheet - Node expects a schedule input and outputs a list of bools:

![2023-03-14_16-19-16](https://user-images.githubusercontent.com/90225478/224903612-1c5d820e-5d68-40c9-96c2-f56f86634edc.png)

Is it intentional that the node function changes but the name and ID remain?

**Comment by erfajo** [comment]
That is correct. As I announced on LinkedIn and in the Dynamo forum when I passed 1100 nodes… I realized that some refactoring needed to take place.

Over the years have I added many nodes, without having to must attention to semantics. I need to do something about that, and this means that some nodes will get a new name, however, it also might have that side-effect that I reuse the name where it is more appropriate.
Schedule.OnSheet is among these… “Onsheet” is a question pointing towards schedules, meaning is a schedule put on a sheet?
The old way is another query of the sheet content of schedules, this is why it is now named “Sheet.Schedule”.
![image](https://user-images.githubusercontent.com/2844374/224911608-628ae337-de84-4d0e-8c40-3ae3eb301cab.png)
I am working all the hours in the day I can on refactoring my package so it is more semantically correct and I hope to finish that before Revit 2024 is released… this is a very hard and condensed timeframe.

Maybe you can't find the post on Dynamo forum anymore, since I asked for a complete deletion of my account due to harassment by some of the moderators in the forum. I simply will not contribute to a forum where they promote that kind of people.

The next release will include a new way for many dropdown nodes and input ports where an enumeration would be the most applicable. I am nearly finished recoding this part all over. This will also give a much cleaner and more consistent usage of data types. I know this will be a completely new way, but I can see that Autodesk is moving fast toward this. Starting with the Spectypes and GroupTypes… in the near future will string values only be used where it is applicable for this kind of type and not where we must parse it to enumeration values am I sure… I will be ahead of that :-)

**Comment by rookiogmailcom** [comment]
Ok, understood thank-you.  I understand the decision you've made, but for users who don't actively follow you on LinkedIn or forums - perhaps a mention of these changes would be possible in your read.me on github? I tried to find in the read.me if any changes had been made regarding the above but couldn't see any so assumed it may be a bug or oversight - when in fact it was actually by design

**Comment by erfajo** [comment]
Normally I have a rather huge "readme" namely the sample collection which is updated and maintained, however, due to the large refactoring job I had to do some shortcuts if I also should be available for bug fixing. Otherwise, should I do it as the dynamo team does it?... not sending anything out even bug fixing and just keeping strict to a publishing plan? I know that users are very satisfied that I am fixing bugs at a fast pace... so yes, some might not find that good but most do.

I will update the graphs in the sample collection asap…
