### ISSUE TITLE
Orchid_203_Revit

### ISSUE THREAD

**Issue by joseph-kirkpatrick** [erfajo/OrchidForDynamo#201]
Manage Node and Package Paths: C:\Users\jkirkpatrick\AppData\Roaming\Dynamo\Dynamo Revit\2.3
Revit: 2020.2.9
Dynamo: 2.3.2.15696
Orchid: 203.6.0.5842

I've tried quite a few ways to get this to work, including searching previous posts on the github, but no luck.

I'm not sure whats causing the issue. I created the Orchid folder in the "\Dynamo Revit\2.3\packages" location and unzipped the "Orchid_203_Revit" folder into the new Orchid folder. When opening dynamo it shows no nodes though.

If I take the Orchid folder from the 2.6 version and copy it into the 2.3 version part of it at least shows up. I'm not sure if something is missing from the Orchid_203_Revit file or what the issue is. The newer versions supported by the .exe files work just fine, 2020 is just giving me the issue.

It also shows that Orchid is in the packages at least but no nodes on the left.

![Screenshot 2023-05-16 144620](https://github.com/erfajo/OrchidForDynamo/assets/32959656/7976471f-fed8-4995-ab78-4753b88f3aa0)

**Comment by erfajo** [comment]
I am sure your problem is "blocking"
https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md

IF you use 7zip and unzip your zip file to your desktop, all files will be "unblocked", and then you should be able to move the files into the proper location afterwards. I am not sure how other zipping tools work, but try to see inside the help in the tool you use. If you use Windows as is, then i does not handle "blocking" at all...
