### ISSUE TITLE
Bulk purge families in directory, save & delete backups

### ISSUE THREAD

**Issue by laurenskruger** [erfajo/OrchidForDynamo#204]
Revit: 2021.1.7
Dynamo: 2.6.2
Orchid: 206.6.0.8434

### The issue
HI - it's my first time posting here and hope you can advise.

I've created a Dynamo graph using loads of awesome Orchid nodes to perform the following steps:
1. Background open .rfa files from a directory
2.  Purge the family document
3.  Close and save
4.  Delete background saved documents from the directory.. ie, 0001.rfa files.

It works really well when the directory has a small number of rfa files. 
Please see image attached.

![BulkRFA_Purge_DeleteBackups_2023-05-23_05-01-42](https://github.com/erfajo/OrchidForDynamo/assets/44587983/03d1cd8b-2195-4170-9e7d-a2cf88026b4e)

I just ran the script on a directory containing 180 rfa files and it ran for a few minutes before Dynamo Player said it had completed with errors. When I closed Dyn Player, Revit looked like it was still running the script (flashing text in the bottom left corner as occurs with the background open documents).  I attempted to check the directory to see what family the script got stuck on, but received a dialogue saying the drive could not be accessed. 
After closing out of Revit, I checked again. The drive took a minute or so to become available. 

I think the script was still running despite Dynamo Player saying it had completed (with errors).  Also, when I closed Revit, I think this may have caused the script to stop and affected my access to the folder directory. 

I wonder if you have seen this behaviour before, have any tips or advice? 
Should I just stick to using the script on a small number of files at a time to be safe?
I can leave the script to run longer after Dyn Player says it has completed, but I'm not sure how I would know when it's truly done?

Any insight would be much appreciated and, thankyou for your amazing package!
Cheers,
Lauren

**Comment by erfajo** [comment]
Thanks for using the proper term "Graph", in the beginning... it hopefully is graphs you mean all the way through.
It is correct you may run into problems when opening files in the background, it all is depending on the processor, the amount of ram, and the computer as such.

Your problem is that it is graphs we work with, and graphs have the problem with the “closing” issue. This means that while processing does the next part in the graph not know if whatever it gets is the complete dataset or just a subset. We have no options to ensure this other than inset some "slowing" mechanisms.

If you look at the dynamo forum, then newbies tend to argue that using Python nodes is best, that is not true, but they need a translation from Python to .net and this is a slowing factor that in many cases is enough to give the feeling of security for datasets. But it is not a solution a all, it is better to remember which problems graphs have and act according to that!

One option is to add in your graph that it only opens what you can control is working, and this could be 10 or 20 or 30 files at the time, and then enter a new number for the next series and then rerun the graph.

try the below, and edit the "num" value to 10 at next run...
```
num = 0;
data[num..num+9];
```
![home](https://github.com/erfajo/OrchidForDynamo/assets/2844374/52ca19df-55f3-4c5a-b0ef-738d6d63a7fd)

**Comment by laurenskruger** [comment]
Thanks Erfajo! I'll try your tips today & let you know how the graph goes. 
I'm getting more RAM today so hopefully that will help. 

Could you also expand on what are the differences between the 2 inputs (fam document vs completely) in the purge node?

I can't seem to find a thorough description anywhere.

**Comment by erfajo** [comment]
try right click and see help
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/9f3d4835-d5a2-4f19-b4c4-14350b1c100f)
