### ISSUE TITLE
Orchid for Revit 2022 - Null outputs only

### ISSUE THREAD

**Issue by maruyamaedson** [erfajo/OrchidForDynamo#207]
### Operating system
Windows 11

### Revit and Dynamo version
Revit: 22.1.40.58
Dynamo: 2.12.1.11123
Orchid: 212.4.0

### What did you do? 
Successfully installled. Tried both via installer and manually.

### What did you expect to see?
Expected to be able to use Orchid nodes normally. Got it working before and in other Revit versions.

### What did you see instead?
The Orchid nodes show all up, but all the nodes return 'null' value. Even the "About.Info" node. It was working like a month ago, but had to format my computer and I think Revit got updated, not sure.

**Comment by erfajo** [comment]
I have tracked it so far, that I can see that the nodes as such do work, however, not if you open a new canvas and put some nodes into it and the app is set to “Automatic”. If you change to "manual", before adding nodes, then it works.

Do also try just to add some nodes to a canvas, try using some of the “InDocument” nodes, since they take whatever is in the document. Then save the graph, close it, open it, …and it works. You don’t even need to set the run option to manual.

![Home](https://github.com/erfajo/OrchidForDynamo/assets/2844374/d51eba3c-41e4-46bb-a93c-b572fba7b033)

This is why I don’t get the error when testing, while I have my testing files created and do only test on build graphs.

The problem arrives somewhere when a dynamo graph is not yet saved, I will try to see if it is something on my side of the desk or if it is an error that the dynamo team should address.

**Comment by maruyamaedson** [comment]
Sorry not answering before, I was out of office.

Yes, I can make it work following the steps you mentioned. 

I will report in Dynamo forums, because it affects running the script via Dynamo Player, or a pyRevit toolbar. It seems it is also affecting Genius Loci nodes.

Anyway, thanks for the quick response!
