### ISSUE TITLE
Document.LoadFamily & SharedParameter.Add error code 0x00000007 contact author

### ISSUE THREAD

**Issue by VerdiSw** [erfajo/OrchidForDynamo#219]
### Operating system
Windows 10 and Windows 11

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 21.1.1.109
Dynamo: 2.6.1.8786
Orchid: 2.6

### What did you do? 
Installed Orchid on PC 1 (windows 11) and copied the C:\Users\#name\AppData\Roaming\Dynamo\Dynamo Revit\2.6\packages folder\Orchid to a server. 
Added this server path to Dynamo on different machines (Windows 10 &11). 
Ran a script with the nodes:
- o|Document.Current    =    DC
- o|Document.LoadFamily    =   DLF
- o|SharedParameter.Add   =    SPA

### What did you expect to see?
The different nodes working correctly

### What did you see instead?
On PC1 (windows 11) where the packages are on the local pc and server the DC node gives a null without becoming yellow and the other nodes work perfectly.
On PC2 (windows 11) where it only reads packages from the server the DC node also doesnt work. DLF & SPA gave the warning 0x00000007 contact author. When installing Orchid on the pc itself DLF & SPA worked correctly. DC did not. 
On PC3 (windows 10) where the package is on the server DC doesnt work and DLF and SPA give the contact author warning. 

![image](https://github.com/erfajo/OrchidForDynamo/assets/152521543/1a1b8b5a-bb42-4482-b992-fecc78aa6ded)

![image](https://github.com/erfajo/OrchidForDynamo/assets/152521543/5f30ed9e-efd3-4a0e-95ca-b7bcb91780c6)

**Comment by VerdiSw** [comment]
Update: 
After placing the issue in Dynamobim I got a tip to install the package locally on all machines. So far I have installed it locally on these 3 machines and all the nodes except the DC node work.

**Comment by erfajo** [comment]
This is an interesting case for me, could I ask for the Orchid version? the current version is 2.6.7.6080

**Comment by VerdiSw** [comment]
Orchid 2.6.7.6065. I have downloaded it on 24 november 2023.

![image](https://github.com/erfajo/OrchidForDynamo/assets/152521543/f8b9a43b-a4e1-46c1-acb4-56613ab7c364)

Thank you for the response. I will check the error page and check if the local location is trusted.

**Comment by erfajo** [comment]
Thanks...
I am especially interested in errors just now since I made a completely new way to code my package. I have refactored my entire environment lately, so if there are any errors I have to figure out if this is due to the "new way" or something else.

However, one of the great new things is, that I only have one executable that installs all versions or the specific selected version(s).

And with the new way of doing it, I could also release Orchid for Revit 2019 and 2020, but I chose not to. However, I am considering that in the next version to maintain my package for Revit 2021. Meaning, I am considering having my package for Revit 2021, 2022, 2023, 2024, and 2025.

However, your latest image tells me something is wrong since you got null returned!?

**Comment by velichkoleg** [comment]
Hello. I have the same problem. The error still persists. Some nodes are not working. And some are not added to the screen at all, they have an icon like in the screenshot
![image](https://github.com/erfajo/OrchidForDynamo/assets/157128515/643d4734-b4ce-4b6a-a1f4-858bafca5717)
