### ISSUE TITLE
Nodes are Missing the dyf folder 

### ISSUE THREAD

**Issue by bitDubai** [erfajo/OrchidForDynamo#22]
I have installed the orchid package (Download from https://github.com/erfajo/OrchidForDynamo) on my Computer if I am not wrong the node files are missing on the right folder. could you please check the below image

only one node found in the folder
![image](https://user-images.githubusercontent.com/47352760/52270609-e9ee1300-295a-11e9-8be3-9629e030a9c8.png)

dynamo version
![image](https://user-images.githubusercontent.com/47352760/52272469-57507280-2960-11e9-924f-20b91df5660d.png)

installed orchid package 
![image](https://user-images.githubusercontent.com/47352760/52272501-6d5e3300-2960-11e9-8b13-437fb9bf935e.png)

**Comment by erfajo** [comment]
There are no dyf files.... and if you have the readme.dyf then it is because you have installed it from the package manager first. This one dyf file should be deleted by my installation, since there is no need for that file at all. If it dosnt do that then I have to look at my installer again.

All nodes in my package is controlled by binary assemblies in the bin folder!

**Comment by bitDubai** [comment]
Thanks for the Respond.
I am a very very basic user of dynamo. your nodes are very helpful for my work

Could you see the image? As my knowledge, The Orchid nodes are missing. 

![image](https://user-images.githubusercontent.com/47352760/52319748-dbe4d480-29e4-11e9-910f-e6eb8c3646ab.png)
![image](https://user-images.githubusercontent.com/47352760/52319935-b73d2c80-29e5-11e9-935e-5071cec2ede6.png)
