### ISSUE TITLE
Manual Installation Issue 

### ISSUE THREAD

**Issue by dieinamood** [erfajo/OrchidForDynamo#224]
The company that I work with uses Revit 2022 and Revit 2023 versions and, for me, it's irritatingly inconvenient creating tickets with all these admin permissions for a simple installation of free software extensions and other things. That is why I opted to manually install this package instead. But then I have encountered some problems.

Revit 22.1.50.17
Dynamo Revit 2.12.1.11123
Orchid_212_Revit

For this version of Revit and Dynamo, I followed the instructions on README with the above-mentioned version of Orchid. I don't quite seem to understand why it says, 'Failed to load library' and 'contains a package without a header.' Please see image below.

![Orchid](https://github.com/erfajo/OrchidForDynamo/assets/154967161/c92249e3-0469-47c4-8a74-bd229f61139d)

Also, for the later version of Revit and Dynamo, Orchid does not appear on the addons and has an error status on Package Manager.

Revit 23.0.11.19
Dynamo 2.13.1.3891
Orchid_216_Revit

![Orchid Package](https://github.com/erfajo/OrchidForDynamo/assets/154967161/8845e8eb-ab4b-4065-b5a7-5c1e30f91baf)

Thank you in advance.

**Comment by erfajo** [comment]
This is the most common error you then will jump into... namely that Windows is blocking your assembly files. Try to read my error page and then open the assembly files and remove the blocking from the files.

As I write, and what is the same case if you download the dynamo sandbox version, you can use 7zip and while unzipping remove the blocking. As I remember it, the dynamo teams have a page describing how to unzip the sandbox version and run it... mine and everyone else's assemblies you download as a zipped version are blocked exactly the same way.

The way around it is that your company acknowledges that we take care of that in the installers… but I do know that IT departments want to shield everything, and I also understand why… so that is why you need to understand how to get around it, not only my assemblies but everybody’s assemblies.

**Comment by dieinamood** [comment]
The day after I posted, I tried disconnecting from company network and turned off the Wi-Fi before unzipping the files and proceed with the installation instructions. It works perfectly fine since then.

You were right and I apologize I didn't realize it was caused by Windows at that time.
