### ISSUE TITLE
How to set types colors with Excel?

### ISSUE THREAD

**Issue by HLDoukeishin** [erfajo/OrchidForDynamo#234]
Revit, Dynamo and Orchid version
Revit: 2021
Dynamo: 2.6.2.18430
Orchid: Orchid_206_Revit

The issue

I tried using FamilyParameter.SetValue to read string/value to set the color of a type, but it didn’t work.

The warning said: The FamilyParameter.SetValue operation failed. The object reference is not set to an instance of an object.

Is it only possible to set colors by reading RGB values? Can materials set in Revit be directly selected and used by their names? Please give me some advice. Thank you very much.

![PWP_20240214_color_2024-02-14_03-48-19](https://github.com/erfajo/OrchidForDynamo/assets/145655141/70c0155f-a34f-430c-a187-383e6e2a89e5)
![image](https://github.com/erfajo/OrchidForDynamo/assets/145655141/9559311a-c41c-476e-8567-8504b5874181)

Here is my files.
[Paragraph-6540_Mb_BK_平行スタックテーブル.rfa.txt](https://github.com/erfajo/OrchidForDynamo/files/14276178/Paragraph-6540_Mb_BK_.rfa.txt)
[Paragraph_D450_2024List_BIMvr2021.xlsx.txt](https://github.com/erfajo/OrchidForDynamo/files/14276180/Paragraph_D450_2024List_BIMvr2021.xlsx.txt)
[PWP_20240214_color.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/14276182/PWP_20240214_color.dyn.txt)

**Comment by HLDoukeishin** [comment]
After using this node, I was able to change the color. Is this the best method? If I want to simultaneously modify other parameters, can I just link them together?

![image](https://github.com/erfajo/OrchidForDynamo/assets/145655141/c72d15f5-0df1-47d4-873c-4f6963de3a1c)

**Comment by erfajo** [comment]
I am not quite sure what I am answering this time, I don’t get the question!?
So let me start by recommending you download my sample files and try to see if any of them might give you some ideas… I think you can benefit from some more understanding of the basic principles.
Next, my below answers might be wrong, but this is how I interpret your question.

1.
If you want to send a material value to a property that is created as a material parameter, you need to send materials. If you send string values you will get an error. In the ootb nodes exists a “Material.ByName” function, use that.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/9decf85d-6cf5-4c8f-8efe-c34b580e0047)

2.
If you want to change color or something else in a material, then you must work with the Material nodes, not the Family nodes.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/55525f22-749d-470b-8f68-19d6022706bc)

Lastly, why do you still use the clockwork save node? It shows that it is meant for project files since you can't save a family with any connection to a “central file”!?

**Comment by erfajo** [comment]
First, all sample files can be downloaded :-)
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/cada38c7-4f31-430a-bb6e-063dfbc9982e)
...and the datafiles if needed :-)

**Comment by erfajo** [comment]
I will try to answer using your numbers.
1.
Sure that works, since the return value is “Material”, meaning it is sending you the Material back. However, you point to some old code I have, which I have to change… I have been moving towards using types instead of string values (which I used when I started coding years ago). Accepting string values gives me the challenge that I every time is using time searching through the entire file for whatever—in this case a material—and that is a total waste of time. I should instead throw an error telling the user to send the proper type.
You get your material, but you should have had an error, I will fix that asap :-)
Material.ByName is the proper node, since it says, “give me a name (string), and I will return you the Material” :-)

2.
If the property (parameter) is a material parameter, then the proper type is of type “Material”, which is the required “value”.

3.
Yes, I have two SaveAs nodes, one that only can be used for projects, since it has the “central” option, and one for any kind of Revit file…
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/7eea4f9c-e36b-4d9b-9af7-798f7030f97c)

**Comment by HLDoukeishin** [comment]
Thank you for your response. I will try to use the nodes you mentioned to complete my graph.

**Comment by erfajo** [comment]
I have uploaded a new build (6167) today, this includes a refactoring of all Material nodes. 
They do not take string values anymore as input, only proper type input (unless they are called "ByName", these kinds of nodes are still driven by a string value).
