### ISSUE TITLE
PDFexport.ByViewSheetSet could not print multiple print sets

### ISSUE THREAD

**Issue by Crusader36** [erfajo/OrchidForDynamo#237]
**Operating system**
Windows 10

**Revit and Dynamo version**
Revit 2023.1
DynamoRevit: 2.16.2
Orchid: 216

**What did you do ?**
Tried to print multiple print sets at once by providing it as list. I have given filenames for each printset.

**What did you expect to see?**
Different pdf files based on printsets.

**What did you see instead?**
Only first item in the list is printed.

![printset as list](https://github.com/erfajo/OrchidForDynamo/assets/28475716/39bd184f-a949-40b1-b806-5c34da113000)

**Comment by erfajo** [comment]
I will try to test it, but I am sure that your problems are caused by "list level" issues... due to that the node does not take more than one Sheet Set, but several File Names... If you feed the node with a list of file names there is of the same length as sheet sets, then will this in itself give you an error!

I think I must reconsider if I should accept more than one filename, because, if I change that to a single input, then am I sure that you will get what you expect… but I can't remember why I chose this in the first place that there should be more than one filename allowed!?

You could try to work with list level for now.

**Comment by Crusader36** [comment]
Thanks for the quick reply. I checked by providing same length of print set and filenames and it prints only one file. Also, the output is messed up as the pdf filename does not corresponds to the printset. 

I guess you might have given list option on filename because of combine option.

**Comment by erfajo** [comment]
No exactly, do always see what kind of input the nodes ask for. If you provide input in any other kind you need to work with list levels so the input match what is asked for.

What I have to do as the programmer is to consider if the input is the proper input or if I should code it differently.

As for now I do think it works as expected regardless if it is the best way that it should work.

**Comment by erfajo** [comment]
I have uploaded a new build (6169) today, this includes a rebuild of the PDF export nodes, the export node now accepts one file name pr. sheet set or uses the naming rule (hosted in the export setting) for individual file export.
Please notice all the changes…
![PDFexport_R23](https://github.com/erfajo/OrchidForDynamo/assets/2844374/1d8b966b-3524-46c1-9ba4-fa5e1e97ca94)

**Comment by Crusader36** [comment]
Installed the new build and it is working great! I have provided. with list of viewSheetSet and fileName of same length and it is able to print back-to-back. Thanks for the quick help.
