### ISSUE TITLE
I can't find orchid 230 to install in revit 2020.2

### ISSUE THREAD

**Issue by Lipezin93** [erfajo/OrchidForDynamo#243]
### **Revit and Dynamo version:**

Revit: 2020.2
Dynamo: 2.3

### **What did you do?**

I tried to install Orchid through the .exe, but it was only available in the revit 2021 to 2025 version.
I didn't find the Orchid version inside the "zipped" directory here on Github

**Comment by erfajo** [comment]
I can't remember when I renamed my versions. 230 == 2.3. Today I use the same number system as Dynamo for the major and minor build. The filename is 203. I had to rename it this way when I noticed that Dynamo would continue numbering the version +2.10. the latest 2x version is 2.19 (Revit 2024)

Furthermore, before this version (3.0), I only supported the last four versions of Revit, but I expanded that to the latest five. This means Revit 2021 is included and this has been the scenario for the last 1. year. I have not had an installer for the 2.3 version for at least the last year, only the zipped version has been available.

The last time I included 2.3 in compiling was the 5. April 2023, and it will not be updated further than that. Revit 2020 is so far behind the current Revit versions, and there is nearly no one left using this version.

**Comment by DragonTof** [comment]
Bonjour, les gros projets travail encore en révit 2020.2 car les petites entreprise change rarement de logiciel et comme il n'est pas possible de travailler sur plusieurs version de Révit le choix de la version est souvent imposé par le Client et n'est jamais très récente.
Je travail actuellement sur plusieurs projets et Révit 2020.2 est la version la plus récente de Révit que j'utilise.
j'ai tenté de télécharger les zip 203 Core et Révit mais cela ne fonctionne pas (le dossier "dyf" est vide, je ne sais pas si c'est normal).

**Comment by DragonTof** [comment]
google translate :
Hello, large projects still work in Revit 2020.2 because small companies rarely change software and as it is not possible to work on several versions of Revit, the choice of version is often imposed by the Client and is never very recent.
I am currently working on several projects and Revit 2020.2 is the most recent version of Revit that I am using.
I tried to download the 203 Core and Revit zips but it doesn't work (the "dyf" folder is empty, I don't know if this is normal).
I hope the translation will be right

**Comment by erfajo** [comment]
I don't release any dyf driven nodes, all my nodes are driven by assemblies (in the bin folder).

However, using Revit 2020 is quite old, it would be a huge job to maintain such old versions. Many things have changed on the API side. This is why the limit currently is Revit 2021 and Dynamo 2.6.

When the new Revit 2025 was released it was the largest change I have seen, but at the same time, was keeping functions for Revit 2021 doable. That might change when we know what will be released next time. The next version where there is a larger step is Revit 2023, so it might be the case that both Revit 2021 and 2022 (Dynamo 212 and 216) will be phased out in 2025 when 2026 is being released.

You write that the client should demand Revit 2020, that sounds not like a healthy decision. I also strongly doubt that this is the case. From my knowledge is it normally the participating companies there is the problem. Since it is well-known that upgrading means that everyone needs to pay attention to what might have been phased out/changed by Autodesk. 

I am working at a client organization where we own and facilitate +500.000 sqm. Getting such old projects would give a larger update job subsequent. This is why I, without any hesitation, can say that it will not be in the client's interest to get a Revit 2020 project, not at all.

Lastly, downloading a zip file comes with some issues, try to see if any of those are described in the error page, most notably if the assembly files are blocked by Windows!
