### ISSUE TITLE
GlobalParameter.Associate to work with Sheets

### ISSUE THREAD

**Issue by AZnait** [erfajo/OrchidForDynamo#248]
I'm currently trying to associate some global parameters to the sheets using the GlobalParameter.Associate but it seems it does not work with sheets and require only elements. Do not know if there is a workaround for it, that is why I just created this issue as Feature request.

Regards,
Ahmad
![grafik](https://github.com/erfajo/OrchidForDynamo/assets/123269929/799e953b-078b-423c-9186-ec2d9668b8ae)

**Comment by erfajo** [comment]
From the very condensed screenshot, you show me, I can't say anything about what you are trying to do, if that is right or wrong.

But it looks like you are trying to send a list to a node that takes a single element.

This leads me to your problem might be another one that you think it is.

You should try to add a node that verifies the output from your filter node. Try to add Object.Type and see if it should be the case that your output is an ArrayList!? If that is the case then you need to change to output to a list.

I don’t know what has happened in the dynamo team, but I started some time ago to see that outputs became “invalid” while the output did change from list to ArrayList. So I created a node to fix this, and then things worked again.

However, I can see that I need to change the node in general, so it takes a parameter instead of a string value to be sure that the proper input is being sent instead I need to check if a parameter exists or not. That should be tested before the data is sent to the node… I will fix this along the way :-)

![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/66f270d2-db0a-4346-9307-d1ea545ce08a)

**Comment by AZnait** [comment]
sorry I miss read the last part that it requires the parameter element and not its name. Thank you for your response

**Comment by erfajo** [comment]
What!?
Then you don't read what I wrote... changing the node from a string value to a parameter type is something for the future...

I think your problem is you are sending an ArrayList instead of a List… and it is a dynamo problem, not anything you can do something about other than changing the type from ArrayList to List by using my node for it.

**Comment by AZnait** [comment]
I have checked it with already, and it was not an Arraylist, my mistake was that used a string as an input for the global parameter, and it requires the Parameter element itself, changing the string to the element solved the problem.

**Comment by erfajo** [comment]
aha, ok, I just saw the image, and there was written "ParameterName" and that is "string", but "GlobalParameter" kind of says "Parameter", so I only need to fix the "ParameterName" to be "Parameter" :-)

The other thing... ArrayList, that might be something you will end up with some day, and now you know what the fix is for that :-)

I mark this as solved :-)
