### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by boiiinng** [erfajo/OrchidForDynamo#255]
Hi, 

We have tried to use both the .exe and manually unzipping the files to the Dynamo folder but we cannot get Orchid to show up in the package list.  Any ideas on what could be preventing it from working?

**Comment by erfajo** [comment]
that sounds strange... can you verify that the files are being "unpacked" into the default package folders? and that you have these folders as your search folders?

the default package folders are like below for the 2.19 version 
%userprofile%\AppData\Roaming\Dynamo\Dynamo Revit\2.19\packages
a snip from the folder holding all versions you may have installed.
![image](https://github.com/user-attachments/assets/daea8732-5d9b-403f-8c97-2e8a46e4d372)
a snip from dynamo preferences
![image](https://github.com/user-attachments/assets/0d28c886-910c-4d36-bfed-ee02c4d181b8)

**Comment by erfajo** [comment]
This is kind of interesting for me, unfortunately, I am not sure it is that for you.

I have never had any opportunities to test my package in a WMWare situation, so I have no idea what to do in that case. I have many functions that go to the edge of using the Revit API, this is why every version I release is coded toward a specific version of Revit. This even encounters that it is always toward the latest service pack of any Revit version. What errors might occur in a WMWare environment do I not have any clue about.

Can you try to go into the package and try to load the assemblies manually? This can be done if you load directly from the “bin” folder in the package. What kind of error do you get?

**Comment by boiiinng** [comment]
Fixed it.  When I tried to load them manually I got error code 0x80131515 which refers to files being blocked when downloaded from the internet.  So I went into the zip file properties and unblocked it, then re-unzipped them to the folder.  Everything loaded after that.  That was the reason the exe didn't work either. Thanks for your help!

**Comment by erfajo** [comment]
Thanks for informing me, I can conclude that using WMWare gives the same errors as if you had done it the normal way when downloading the zip files. Just for the record, that was one of the error possibilities I have written in my  [error](https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md) page.

But what could I have done to do this better? In my installation, I use the known default location that comes with Dynamo, since those who use the installer don't have the knowledge to load it manually. In other words ”use default out of the box”.

But I could add something like ”unzip” content to the desktop, and from there could the content be moved manually to the proper location, would that be useful? By doing that would assemblies not be locked, as they do automatically when it comes using the Windows zip tool.

And just for the record, if you had used 7zip you can set it as an option that files should be unlocked during unzip. As I remember it, this is information written on the page where you can download the dynamo sandbox version… maybe I also should include that :-)
