### ISSUE TITLE
Updated orchid. But i get al kind off namespace collisions with the OOTB nodes in code blocks 

### ISSUE THREAD

**Issue by fnstegeman** [erfajo/OrchidForDynamo#28]
### Operating system
(e.g. Windows 7,)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2019.2.
Dynamo: 2.03.
Orchid:  tried the most recent update off Orchid

Hello Erik

### What did you do? 
Updated Orchid

### What did you expect to see?
No problems with OOTB nodes in code blocks

### What did you see instead?
A lot of OOTB actions in the code blocks are giving a namespace collision. 
So i went back to the old orchid installation. (Orchid 200.2.0)

Nico

**Comment by erfajo** [comment]
I know. I am aware that the Dynamo team has changed something concerning how assemblies are being read. Therefore am I working on a total re-coded version, but this has another drawback. Migration is not working internally in Dynamo 2.x. Meaning, I have to wait to release the updated version until Revit 2020 is released due to Dynamo is not being updated with an installer anymore.
