### ISSUE TITLE
Parameter.AddSharedParameter Toggle Create New

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#31]
I'm worried that creating a parameter by mistake will happen if the wrong person in our firm messes with this node. I don't want to constantly have to clean up our shared parameter file and track down who is accidentally adding parameters. I've ran into an example while upgrading from 2.0 to 2.1 where a missed use level toggle on group name caused duplicates of parameters to be created under different groups.

I think having a toggle for create new would be desirable. If the toggle is false then any parameter that doesn't exist would simply not be added to the family. Perhaps you could add a output for parameter not added.

I've also considered suggesting creating a new node that simply doesn't have the create function built in. 

Either option I think would work. Appreciate all the work you do on this package. I use it a lot. Thanks!

**Comment by erfajo** [comment]
I am not sure I quite understand... So to my information, what you suggest is "read-only" and "write" as an option to the SP file? or is it only a problem in the files?

If it is only in the files, then would a toggle not prevent anything. A boolean toggle could also be set and forgotten in a state where you would end up with unwanted parameters.

If it is preventing for writing a new parameter to the SP file, could this then be solved by user rights to that file? Controlling it from inside Dynamo could be fixed but it seems to be a minor problem since most users would want a node for creating parameters and adding them if they don’t exist in advance. But I could create the latter if you really want it.

**Comment by Crapai** [comment]
Yeah I guess it could be handled with permissions. Editing a shared parameter file in Revit doesn't bypass normal file restrictions?

I think having a separate node would be the safest but if I can handle it with permission then it would just be a problem for me. I just need to be more careful while making/editing scripts. lol

If you want to create a different version that would be great, if not don't worry about it. I don't want to force more work for you if it is something most people wont use. Thanks for the quick reply by the way! :)

**Comment by erfajo** [comment]
What asked for, preventing users to edit the SP file?

**Comment by Crapai** [comment]
That is correct.

**Comment by erfajo** [comment]
I have changed my nodes for project and family so AddSharedParameter only adds parameters which exists in the SP file, and I have made new nodes named CreateSharedParameter which both add parameter and create them if they dont exists in the SP file... I think this is the most clean way to do it.

the new build is named 7072, please test the it and give feedback :-)

**Comment by Crapai** [comment]
Great, Thanks. I'll test it out tomorrow and get back to you.

**Comment by Crapai** [comment]
Just tested it out in 2.0 and 2.1. It works great at adding the parameter to the family and not adding one to the SP file if it doesn't exist. I really like that the error tells you which parameters were not added. 

As a note when I upgraded the 2.1 script was fine, but there were several nodes in the 2.0 that were unresolved. I can't remember if I was just using an older version in 2.0 and the unresolved status was from an version you made before this.

**Comment by erfajo** [comment]
I had to move on at some point… I held a lot of development back waiting for the Dynamo team to fix the migration problem in the Dynamo 2 series... It is simply not working!
I have complained that this is a problem, but I don't think it is being evaluated as a problem for the dynamo team since we still have the problem.
If you had your graph in a 1.3 series environment, then would this not have been a problem... in the 2 series you need to edit your graph file with search and replace in a text editor.
I made a post about this at the forum, showing how to manually migrate... if you want to know more
