### ISSUE TITLE
Latest Orchid with Revit 2017

### ISSUE THREAD

**Issue by Schindi11** [erfajo/OrchidForDynamo#36]
Hello Erfajo,

I want to update your package to the newest but unfortunately I think this is not possible anymore to use with Revit 2017?
E.g. on the Document.BackgroundOpen I get the following error: 
"The type initializer threw an exception"
Is this kinda Problem of the Revit Version that its not compatible anymore or is this some other bug?
Thanks for your Help

Revit: 2017.2.4
Dynamo: 2.0.3.8810
Orchid: newest

**Comment by erfajo** [comment]
You could be right... I have not Revit 2017 anymore. Furthermore, after the update last year to Dynamo 1.3.4., did I assume that it would work for Revit 2017 as well.
Could you make som screendumps with the error showing up, and maybe share the graph?
I am not sure how I can test the environment anymore, but I will try to see what I can do.

**Comment by Schindi11** [comment]
Hi, of course I can share this. I always get the same Exception. See here e.g. with Document.BackgroundOpen and Document.Name.
![image](https://user-images.githubusercontent.com/43644233/60564901-bb396480-9d61-11e9-96e2-b5fb66d3dbbb.png)

I also tried already to remove all other Packages and Add-Ins for Revit, didn´t help. 
Also when I start up Dynamo, I get already the following Dynamo Notifications: 
![image](https://user-images.githubusercontent.com/43644233/60564943-ddcb7d80-9d61-11e9-9fb8-37a7886e87e1.png)

I´ll copy the whole text in a seperate Textfile, it hopefully can give a hint :)
The latest Version that was still working for me was from March this year. (But I didnt test any further version)
[Dynamo File Load Exception.txt](https://github.com/erfajo/OrchidForDynamo/files/3353372/Dynamo.File.Load.Exception.txt)
[Graph.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3353373/Graph.dyn.txt)

**Comment by erfajo** [comment]
I can see that you have installed the 203 version, and this will surely not work. In first line of the error description it says you are trying to load 203.1.0.7117
You must download the 134 version

**Comment by Schindi11** [comment]
To be honest I dont understand why it´s not working, Whats the cause for that?
I mean I was using your Package till March on the 201 Version without any Problems. The thing is that I also use Dynamo with Revit 2018 & 2019. Therefore I think it´s not a good idea to go back to 1.3.4 on the Revit 2017.

**Comment by erfajo** [comment]
Hopefully, should the 134 range cover 2017 since this range has not any changes in the API compared to 2018 up to 2018.3. However, due to I do not have the 2017 version anymore, are new nodes coded and tested in Revit 2018.3 since this is the lowest version I have access to. So I can't guarantee 2017 is still working. If you can confirm that 134 does not work in 2017 will I change the version range. I will not do anything to support 2017, since I can only cover the three latest versions due to workload.

When Revit 2019 was released last year I started coding towards this API. The 2019 API was a “transition” version where some features were announced to be deprecated with the 2019 version and new API was introduced (some of it worked also in 2018.3 version). This means that over the last year have I coded towards 2018.3 as the minimum version.

That is also why I rather easily could upgrade to 210 version with nearly the same code as I have for the 203 range. I think many others have challenges to support 2020 if they also will cover below 2018.3 in the same version.

All new stuff is coded using 2019 as the main target and coded in the 203 range. I test it in 2020 and I try to transfer the code to 134 to be tested in 2018.3. If the code does not work, then is the node not being released in the 134 version, since I will deprecate this version anyway next year when 2021 is released.

**Comment by Schindi11** [comment]
Alright at least thanks a lot for your detailed explanation, brings a lot of light in a non-programmers brain :)
I am downloading 1.3.4 right now and I´ll let you know the outcome.

**Comment by Schindi11** [comment]
Tried now the 1.3.4. same Result......
![image](https://user-images.githubusercontent.com/43644233/60649353-1f335a00-9e42-11e9-9ff8-108f8ffcbe5a.png)

I can confirm that the latest Package works with Revit 2018.3. I just tried it also to be sure it´s not something else on my machine.
![image](https://user-images.githubusercontent.com/43644233/60650507-923dd000-9e44-11e9-81fd-3a952b8009da.png)

So for me now I guess I´ll stick with the Orchid Version from March (202.4.1.7010) where still all Nodes work with Dynamo 2.0.3 and Revit 2017.

**Comment by erfajo** [comment]
Let me try to see it once more if the 134 also gives troubles.

**Comment by erfajo** [comment]
Good news... I found the error, the bad news is that I need to get an idea how to solve it.
first the good news... the code for background open has not changed, and work as expected... BUT the bad news is, that I have one new method in the same csharp file which is only available from 2019 and beyond. This one method has the bagside that it prevents any of the other methods to work under 2017. So I need to find a way so I can have files containing methods for the different revit versions to support 2017.
I have an idea I need to test and then will I return back.

ps... I had to install Revit 2017 to figure this problem... that took some time

**Comment by Schindi11** [comment]
Thanks for your investigations, i really appreciate it and it would be very nice if you could solve the Problem :) I guess I´m not the only User of you package.

**Comment by erfajo** [comment]
Could you please try the 7125 build? please try both 130 and 200 and give feedback if it work...

Thanks for the feedback, It gave me som new ideas how to solve some of the conflicts it gives supporting parallel version :-)

**Comment by Schindi11** [comment]
Hello erfajo, sorry for the delay, unfortunately I was very busy the last 2 weeks.
Anyway today I got some time to test. On the first test everything seems to be fine with both Versions 1.3 and 2.0 with Revit 2017. 
![image](https://user-images.githubusercontent.com/43644233/61628183-e1c42e80-ac81-11e9-9187-f43b484b5839.png)

![image](https://user-images.githubusercontent.com/43644233/61628191-e852a600-ac81-11e9-908b-cb9eab4abb3c.png)

Thanks a lot for the changes, I really appreciate it. 
If I find something else during my work, I am gonna come back to you again to report :)

**Comment by Schindi11** [comment]
on thing I noticed now is that the Selection.ElementByCategory Node doesnt work anymore for Materials. This node worked quite well in the old version.
![image](https://user-images.githubusercontent.com/43644233/61637896-a2550c80-ac98-11e9-921a-cd89afd2675d.png)

**Comment by erfajo** [comment]
I seems that this issue is obsolete since I dont support Revit 2017 anymore. I will close this issue.
