### ISSUE TITLE
Installer for 2.2

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#41]
Is there a installer for 2.2. We updated our Revit which updated Dynamo and now half my script are broken. Not an issue with other packages because they can be copied or downloaded again from withing Dynamo.

**Comment by erfajo** [comment]
I try to have an installer for the released versions. To have installers for future versions has become an increasing challenge. This would at the time being include that I should have installers up to version 2.5.

Besides, I have to admit that I do not follow all the future version since they become more and more beta the higher the number. My time has become more limited and that’s why I only follow the released versions. First when I recognize that a new version is going to ship off, then will I start to include it in my development.

But as you have figured, the assemblies for 2.1 should work with the future versions.
