### ISSUE TITLE
Document.TransferByType

### ISSUE THREAD

**Issue by sarah9090-ui** [erfajo/OrchidForDynamo#53]
when i runing the node Document.TransferByType
i get this 
"Warning: Document.TransferByType operation failed. 
Attempt to modify the model outside of transaction."
so how can i fix it

**Comment by erfajo** [comment]
wups... You should not end up there. I will take a look at it asap.

**Comment by sarah9090-ui** [comment]
hi erfajo
I need to transfer the data from one file to 16 file without open the 16 file because it will take so many time to open

Thanks and best regards
Sarah
![4b370bab4602ec71bd0415a61cf051d5a62f083b_2_690x198](https://user-images.githubusercontent.com/58312877/69892049-1a4bd700-130a-11ea-9830-a940070f5e82.png)

[Document Transfer By Type.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3906489/Document.Transfer.By.Type.dyn.txt)

**Comment by erfajo** [comment]
thanks for showing the graph file, this should always be a part of an issue.

I am afraid it is the combination of nodes that gives you the error, since you open an transaction where it is unwanted, I think this fives you the error.

I have tried to correct your graph, try to se if it works., there is one place where you turn types into strings, I dont think that is needed.

![Document Transfer By Type](https://user-images.githubusercontent.com/2844374/69900378-bdd0d200-1372-11ea-8d42-7e2fc2d1eeae.png)
[Document.Transfer.By.Type.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3907086/Document.Transfer.By.Type.dyn.txt)
