### ISSUE TITLE
Installing Issues/Issues After Restarting Computer 230

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#57]
Windows 10

Revit: 2020.2
Dynamo: 2.3
Orchid: 230.0.0.7288

I've tried multiple things to update Orchid:

**1. Manual Copy**
I tried to update to 230 manually buy copying the files from "OrchidForDynamo-master\Orchid_230\Dynamo_Revit" minus the dyf folder which only has the delete me file. I copied it to this directory, "C:\Users\cjr\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Orchid"

I then opened a...ahhh file which has Orchid nodes and got the WorkspaceDependencyViewExtension screen that notified me that Orchid has issues.

Orchid nodes have this warning" Warning: Node of type 'Unresolved' (C:\Program Files\Autodesk\Revit 2020\AddIns\DynamoForRevit\DynamoCore.dll) cannot be resolved". I've looked at this file but it doesn't seem like it has been modified recently.

Orchid is not in my add-ons list, however if I go to package manager I do see Orchid there.

![Orchid Upadate Issue01](https://user-images.githubusercontent.com/50451766/71091094-7ddf5c80-2172-11ea-8f70-0bc10f818f3c.PNG)

**2. Ran .exe installer**
When I've tried this I've gotten similar errors. I looked in my package folder and the orchid folder is not there. There is however new Revit and Core folders under the dynamo folder as well as an uninstall exe for Orchid. This has done this while installing it from a network drive and from my desktop.

**3. Copy From Dynamo_Revit to Dynamo Revit**
I finally copied the Orchid folder from the "Dynamo_Revit" fold to the package folder of the "Dynamo Revit" folder. When I do this is has worked.

**Update:**
I believe I went through similar events yesterday, but I wasn't quite sure so I restarted my computer to try it again and the Orchid package appears broken again. I deleted my Orchid folder and did method 3 again and the package works again. It appears every time I restart my computer the package gets broken again.

**Comment by erfajo** [comment]
I make regulatory tests on all versions, and I can't reproduce the error you mention. However, I know if some other package has included any of the core dynamo files, then is there a problem!

try to search for "DynamoCore.dll" in you root package folder and see if any other package has included these kind of files.

**Comment by Crapai** [comment]
Thanks, for the help.

The Simplex package has "DynamoCore.dll". Is there a way I should handle this issue?

**Comment by erfajo** [comment]
yes simply delete the dynamo core files... as DynamoCore.dll

it should be dynamo that takes care of the proper assemblies for dynamo.

I am sure it is a mistake that "Simplex" package has included these files, so please warn them...

**Comment by Crapai** [comment]
I removed the DynamoCore.ddl from simplex yesterday. When I started dyanmo today it still had the same issues. I still had the "Dynamo_Revit" folder that the install did so I copied it from that back into the 2.3 package folder and it started working again. 

It's almost like something is happening in the actual 2.3 Orchid folder that is wiping out or altering some file needed for dynamo to recognize the package. The only thing I can think of is Synchronicity which I'm using to copy my packages to a network drive for distribution purposes. It's been running for about a month without issue and I'm only running into this since I updated from 210 to 230 Orchid. I'm still going to disable it today and see if I have issues tomorrow morning.

**Comment by erfajo** [comment]
This sounds like it is on your computer something is happening!?

if you can copy files you have downloaded from Github, and move these into the folder, and it then starts to work. When you then restart your computer and it doesn't work, but when you recopy once again then it works... then it must be on your computer something is wrong.

try to see the version the assembly (dll) files have in the Orchid folder when you restart again, to see the version number if this is the same as the one you have stored locally. If these are not the same, then you need to figure out how/why this can happen. OR try to figure out what else could be the problem.

As mentioned, I cant replicate your issue, so I cant see how I should be able to help you.

**Comment by nlv123** [comment]
Hello! I use this topic because I have a similar error. I'm using Revit 2019 and Dynamo 2.0 (Orchid 2.0.x)

Some nodes appeared as unresolved and I can't find a reason. I installed Orchid from the .exe, I tried to copy the folders into the proper folders and I tried to search a duplicated  "DynamoCore.dll" package but there are none.
![1](https://user-images.githubusercontent.com/58989229/71251026-71e5cd00-2321-11ea-8fe8-d9c2c1d9e75a.PNG)
I suspect there's a problem with my folders but I'm not sure about it. When I installed Orchid the folder "Dynamo_Core" appeared when before wasn`t . Do you think is a package problem or the package don't exist anymore?
Thank you in advance
![2](https://user-images.githubusercontent.com/58989229/71251330-5a5b1400-2322-11ea-83a6-c5530450459a.PNG)
![3](https://user-images.githubusercontent.com/58989229/71251332-5a5b1400-2322-11ea-954a-ddca521b6595.PNG)

**Comment by erfajo** [comment]
As I mention, please verify that no other packages has included the core dynamo assemblies.

My package is coded directly towards each version, meaning you gain most if you has a dynamo 2.3 and my Orchid 230. I dont think that there is that many who do this, and if they by accident include the dynamo core assemblies then will unexpected things happen. Among those, will my node fail, but this can happen with any package there is coded directly towards a specific version.

But what you @nlv123  is writing seems to be another problem there has nothing to do with this issue... in your case does it look like you need to refind the node in the package.
If it is a very old version of Orchid, then is the node most likely moved. Since migration doesn't work with the dynamo 2.x version I cant help you... try to google migration problems with dynamo 2.0 and you will find plenty.
Another time, please make an new issue en inset reference to this if you think it is the same... which it is not!

**Comment by nurialar** [comment]
Hi, sorry but I lost my last account (nlv123) 
I've uploaded Dynamo into 2.3 version and I'm using another PC in order to make sure is not a single PC's problem (at least, my previous PC) 
Now some nodes are working but another ones aren't. I tried to search "Orchid.dll" into the package but there are a lot of files with similar name (but not exactly "Orchid.dll") 

![1](https://user-images.githubusercontent.com/59205416/71449782-c7bcd980-2754-11ea-9c0d-48f957849824.png)

Hope there will be a solution ....Thank you in advance!

p.d: I'd guess this is a very related question so I keep posting into this topic

**Comment by erfajo** [comment]
I have changed the way I release the manual installation. It is now a zip file including all what is needed for a version. Please check out the default page, there is a small exeplation available.

**Comment by Kynikx** [comment]
"> **3. Copy From Dynamo_Revit to Dynamo Revit**
> I finally copied the Orchid folder from the "Dynamo_Revit" fold to the package folder of the "Dynamo Revit" folder. When I do this is has worked."

I could not get my Orchid to work no matter what I did, until I read this thread, specifically step 3. Thank you! :D

**Comment by erfajo** [comment]
That problem should not occur anymore, that was a problem I made up when I converted from giving the files individually here at Github.
The files are now provided as executable and zip files... I had too many who didn't read the difference between the Core and the Revit version.
However, as a part o that, I needed to change the folder name to include an underscore to make it productive for me when I publish. The first version released after that had the "underscore" issue. This was solved very fast afterward.

**Comment by Crapai** [comment]
erfajo, I know you don't know what is happening with my issue so I'm not asking for help here. I'm just trying to keep people informed and will hopefully let people know if I find a solution.

Just to let everyone know once I've downloaded the new manual version with the zip files, I haven't been able to get the package to work by copying the files from the download to my "Dynamo Revit" folder. The only thing I've gotten to work is doing the install after each restart of my computer. I've been dragging my feet on getting my IT person to look at it but I'll try to see if he can think of anything today and let people know if we find anything. I might also post it to the DynamoBIM forum and see if anyone has had similar issues.

**Comment by erfajo** [comment]
I hope your IT person can figure what goes on in your computer... Orchid is installed on a huge number of computers at our University, and I have not seen this kind of error at any time. We have a daily procedure that downloads the latest if it is updated, and distribute it in the network.

**Comment by erfajo** [comment]
@Crapai, 
I took one random picked computer this morning to test a manual installation. I downloaded from Github and unzipped the files, I then moved the files to the package folder location, and started Revit/Dynamo.

There were no errors. Revit, Dynamo, and the Orchid package worked as expected.

So I am afraid it is something else which gives you problems. It might be due to your usage of my package to a high degree--and thanks for that--where is where you encountered problems. But I can't replicate what you have described besides my initial mistake with including the underscore in some previous builds.

As I mentioned, I cover five different branches of Dynamo in two versions, those which are corresponding with the Revit versions from 2017 to 2020. Each version is compiled using the exact Revit assembly and the exact Dynamo assembly.
I have industrialized my coding factory to an extreme degree, meaning on the core code side do I only maintain two sets of class files. One for the branches before version 2, which was xml driven graphs, and one for the branches after version 2 which is json driven graphs. The difference between those versions is the default loading in the nodes and the dropdown nodes. Så it is around 30-40 lines of code which is the difference out of thousands of lines of codes.
I then compile the versions into five versions for Revit and five for the Core (Sandbox).
This means, if something is wrong, then would this be the case for all versions… and this is not the case as I understand it.

I am aware that no one else has such a coding factory as I have, I have seen other distinguished packages who have made the error of including some of the assembly files from Dynamo into their package. This must be due to mistakes. However, newbies and codes who are not aware of this are where troubles begin. They might not be aware that including assemblies is troublesome for everyone else.

Do I then not do this? Yes I do, we all have to from time to time. BUT… I have included assembly files that others then hopefully don’t do or I include assemblies that will not give other codes problems. I have included assemblies for my pdf export, for ifc export and for covering Sigma Estimates (software for project estimation). I have been extremely aware of the ifc export since this comes in many versions. How should I ever be able to figure which version a user has!? However, I was lucky that the ifc exporter is loaded prior to Dynamo. This means that whatever assembly I include in my package is being overruled by Revit. The only problem is that an older version of the exporter might not support my nodes. To make it productive for me, have I chosen to write in the nodes help, where there might be a problem. You can try to delete the filed named “ifc” in my package and then start… see if this gives errors. If it does then I have to figure what is going on. But I don’t expect this is the case, the same goes for the pdf exporter and Sigma.

I am very convinced that your error is due to something else.
