### ISSUE TITLE
SpatialElement thoughts

### ISSUE THREAD

**Issue by DynaBimm** [erfajo/OrchidForDynamo#69]
Hello!

Often we have Nulls in Room boundaries, but it's not a Room separators.
SpatialElement.GetRoomBoundary doesn't return closed Room Boundaries. See screenshot, please.
(Also SpatialElement.GetRoomBoundary doesn't work in international Russian version of Revit, but English is OK. SpatialElement.GetBoundary works fine in both). 

And one more good idea from Dynamo forum. Bounding Elements from linked file instead of RevitLinkInstance.

Thanks a lot for your huge work, Orchid has made Dynamo complete! 

![2020-03-31_20-03-06](https://user-images.githubusercontent.com/62960555/78069733-430cd780-73a3-11ea-823b-987d5ebd26df.png)

**Comment by erfajo** [comment]
Thanks for reporting, I will look into it.
I have removed your copy of the code from another package. First it is someone else work and next it is written in Python, I code in C#.

**Comment by erfajo** [comment]
I have updated my nodes for spatial elements... and for Revit 2021 in general.
Since I use the same core engine for all spatial element nodes I had to figure a way to collect and filter elements so the engine could full-fill all requirements. At the same time did I optimize my code severely and run now most of it using Linq. As written before, I can do much more with C# than with Python.

**Comment by erfajo** [comment]
I have included option for linked files now... 7410 build
![SpatialElement](https://user-images.githubusercontent.com/2844374/79343760-1b834680-7f2f-11ea-8ef2-6f1d4103e83e.png)
