### ISSUE TITLE
Associate Parameter in Dynamo with Spring Nodes FamilyInstance Failed 

### ISSUE THREAD

**Issue by xoronos** [erfajo/OrchidForDynamo#81]
Revit: 2021
Dynamo: 2.5
Orchid: 250

### The issue
Hi i read the issue report from associate Parameter in GitHub [https://github.com/erfajo/OrchidForDynamo/issues/14](url)

I tried this package.dyn and it Doesnt work. It says at Parameter.Associate it is not an Objectinstance.
I created my Family with GeometryInstance by Spring Nodes. The result is a FreeFormElement.

It Seems Collector.ElementsofTypeinDocument from rhytmn doesnt work Togheter with Orchid Document.BackgroundOpen/Data.Await/Parameter.Associate.

Is there any solution how to Associate the Parameter from NestedFamily? 

Even the workflow from NestedLookup Load a family(nested) doesnt work...
![Nested-Lookup](https://user-images.githubusercontent.com/65535153/82194998-f8660100-98f7-11ea-8e5b-cfc3f5331e2f.png)

![](https://user-images.githubusercontent.com/2844374/48616493-13b71f80-e994-11e8-880b-e1973e1c084e.png)

![image](https://user-images.githubusercontent.com/65535153/82195187-43801400-98f8-11ea-90e9-e1aff5d249b2.png)

![image](https://user-images.githubusercontent.com/65535153/82195359-7a562a00-98f8-11ea-8905-a5af033b9692.png)

**Comment by erfajo** [comment]
That is correct, you cant combine those two nodes, since the object types are not applicable.
You cn neither feed that node with any Dynamo document nodes. That nodes takes another kind of document node, check the help provided from that package... Likewise would I expect you will get yet another error when you fix the document type. Elementtype is not equal to Types...

**Comment by erfajo** [comment]
That is correct, you cant combine those two nodes, since the object types are not applicable.
You can neither feed that node with any Dynamo document nodes. That nodes takes another kind of document node, check the help provided from that package... Likewise would I expect you will get yet another error when you fix the document type. Elementtype is not equal to Types...

In generel, you need to check what kind of object types a node takes as input and returns as output. in addition can my nodes be combined with most nodes from the dynamoteam, but not necessarily with nodes from other packages, due to types... my types are named Orchid.xxx as dynamo nodes are named Revit.xxxx
most likely will you be able to do whatever you are planning just using the dynamo nodes and nodes from my package. If you miss something then let me know so I can code missing nodes.

In that case just reopen the issue, the problem with how you use combinations of nodes are not able to be solved.
