### ISSUE TITLE
Workflow with Nested Lookup Dynamo Skript Parameter.Associate muliply Nested Families

### ISSUE THREAD

**Issue by xoronos** [erfajo/OrchidForDynamo#82]
Revit: 2021
Dynamo: 2.5
Orchid: 250

### The issue
(Fill in here)

Dear GitHUB Team from Orchid

How can i associate multiply nested Families without open the file, i want to play the dynamo script only in the motherfamily file, see in the pictures.

![image](https://user-images.githubusercontent.com/65535153/82785614-3ff20d00-9e63-11ea-909a-33ecb529b11d.png)
![image](https://user-images.githubusercontent.com/65535153/82785931-d3c3d900-9e63-11ea-85ad-b0d19c1be6af.png)
![image](https://user-images.githubusercontent.com/65535153/82786027-0ff73980-9e64-11ea-920d-216dfcb065fd.png)
![image](https://user-images.githubusercontent.com/65535153/82786143-5a78b600-9e64-11ea-8762-c0eaf28c20b6.png)
![image](https://user-images.githubusercontent.com/65535153/82786266-94e25300-9e64-11ea-9545-40432a67987c.png)
![image](https://user-images.githubusercontent.com/65535153/82800099-658b1080-9e7b-11ea-9d6d-96b68242ccde.png)

**Comment by erfajo** [comment]
First, I cant see any scripting!? However, I see a graph, and presume that you are addressing an issue concerning a graph and not a textual script!?

Next I can see that you have seen my samples, but pay attention towards the "mother" file that should associate all the other families. please feed the associate node with a proper "familyDocument".

If you also want to debug the in/output, you need to freeze the Close node, otherwise will you not be able to see what is going on in the graph. However, this will be challenging, since you will keep on opening files in the background over and over again. If you meet errors on to many open files, then you have to close Revit and start over. 

Therefore, start with a base case, where you have one open mother file file and try to associate two-three files. When this works, then scale up with more files to associate. lastly you need to implement opening many "mother files". The last step involves List Level!

**Comment by xoronos** [comment]
First thank you for the reply!

My fault there is no script. I only need help for the graph.

I tried to connect Family.EditFamily with Document.LoadFamily to get a real familyDocument.

Now it says Looks up a localized string similar to Number of items does not match the number of keys.

![image](https://user-images.githubusercontent.com/65535153/82808658-b22a1800-9e8a-11ea-8027-ce27b751f1cf.png)

**Comment by xoronos** [comment]
![image](https://user-images.githubusercontent.com/65535153/82815833-40f26100-9e9a-11ea-8b78-2a8e617d482f.png)
![image](https://user-images.githubusercontent.com/65535153/82815889-654e3d80-9e9a-11ea-87bb-87ed881010c2.png)
![image](https://user-images.githubusercontent.com/65535153/82815939-84e56600-9e9a-11ea-8ab0-2f6ec6405720.png)

**Comment by erfajo** [comment]
If I am going to help you, then please upload the bare minimum of testfiles... two-three files, and your graph file... add ".txt" to a zip file so it can be uploaded.

**Comment by xoronos** [comment]
[githubtest.zip](https://github.com/erfajo/OrchidForDynamo/files/4693799/githubtest.zip)

**Comment by erfajo** [comment]
I will take a look asap.

**Comment by xoronos** [comment]
i just tried it out sometimes it works after turn off my computer sometimes not... the goal is not to have problems like that... it should work multiply times without turnoff my computer

**Comment by erfajo** [comment]
you have made a series of errors.
first you need to split those files there are going to be loaded and those there are mother files. Most important is, that you need to keep track one which motherfiles who is going to load a range of other families!

in my test did I do it like this!
![image](https://user-images.githubusercontent.com/2844374/83139894-67f4a100-a0ed-11ea-818c-ab642c878a7a.png)

Next, int the "motherfiles" you need to ensure that you have the needed parameter to associate, in you case I created that manually, but I have nodes for this part also, check out the sample collection.
![image](https://user-images.githubusercontent.com/2844374/83139968-8ce91400-a0ed-11ea-93df-249de4e1b1d6.png)

this ended up as can be seen in the below graph
![03 1 4_M_Fam_Familienparameter zuordnen mehrfache Dateien_2020-05-28_02-10-55](https://user-images.githubusercontent.com/2844374/83140048-b3a74a80-a0ed-11ea-9385-756b4e0f93f0.png)

please notice the red boxes, this will work from next time I upload my package, until then you can use those there looks "deprecated" on my graph. They should be correct in your case.

...and next time remember that German is not the international language, You might have written hints to me, but I cant understand them, but since I could see what was wrong, I didnt need them.

the graph file, remove ".txt"
[03.1.4_M_Fam_Familienparameter zuordnen mehrfache Dateien_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4695432/03.1.4_M_Fam_Familienparameter.zuordnen.mehrfache.Dateien_erfajo.dyn.txt)

**Comment by xoronos** [comment]
I added wb_material as a shared parameter in all nested familys with orchid package.

Allgemeines Modell - Würfel is for the subcategory name in my nested family.
![image](https://user-images.githubusercontent.com/65535153/83230926-e5baba00-a18a-11ea-9c19-6de48d426019.png)

it says the objectpath is not on an objectinstance
![image](https://user-images.githubusercontent.com/65535153/83231105-3df1bc00-a18b-11ea-9742-fb085d81cb5d.png)

**Comment by xoronos** [comment]
![image](https://user-images.githubusercontent.com/65535153/83231243-7b564980-a18b-11ea-8465-7b68c301a60f.png)

**Comment by xoronos** [comment]
![image](https://user-images.githubusercontent.com/65535153/83231701-3aab0000-a18c-11ea-88b7-04421e7b4359.png)

**Comment by xoronos** [comment]
[03.1.4_M_Fam_Familienparameter.zuordnen.mehrfache.Dateien_xoronos.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4700192/03.1.4_M_Fam_Familienparameter.zuordnen.mehrfache.Dateien_xoronos.dyn.txt)

**Comment by erfajo** [comment]
Subcategories could be a problem, since this is not OOTB categories driven by Autodesk. However, I will give it a try. I am afraid that It will involve some programming, so I am not sure how fast I can do it.

**Comment by xoronos** [comment]
I setted on all nested familys with no subcategory <Default> bit it doesnt work neither i bet it is because its a freeform

**Comment by erfajo** [comment]
freeform it yet another thing... but I have a solution for that somewhere, i will try to find it

**Comment by xoronos** [comment]
[03.1.4_M_Fam_Familienparameter.zuordnen.mehrfache.Dateien_erfajo_test verdeckte Linien.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4700755/03.1.4_M_Fam_Familienparameter.zuordnen.mehrfache.Dateien_erfajo_test.verdeckte.Linien.dyn.txt)

**Comment by xoronos** [comment]
the thing is my mother family is a generic model and inside of this mother family i instanced freeformelement and saved it as a generic model 
so my free form element is inside a generic model as nested familys

**Comment by erfajo** [comment]
try to see in the sample collection under family, look for "FormSetGet.dyn"

**Comment by xoronos** [comment]
But FormSetGet is not for nested family it works only for document current

**Comment by erfajo** [comment]
nested families in one issue, and freeform or any form is another... if you have nested families there contains freeform, then is it a family issue, not a freeform issue.

**Comment by erfajo** [comment]
I have a kind of lost track in this issue, if this is still an issue, then please try once more to pin the problem. please remember to be precise with the issue. It seems that this issue can be one of many issues.
