### ISSUE TITLE
Sharedparameter.Add - adding all parameters to first item in Built In Parameter Group list.

### ISSUE THREAD

**Issue by sshatswell** [erfajo/OrchidForDynamo#85]
Revit: 2019.2
Dynamo: 2.0.3.8811
Orchid: 203.1.3.7458

### The issue

Hey erfajo. Thanks for the great content. I'm having an issue with the Sharedparameter.Add node. While trying to batch add shared parameters to a family, the node appears to add all the intended shared parameters, but lumps them together in the first group type of the built in parameter group. Is this a known issue, or am I missing something?

Appreciate the help!

![Sharedparameter Add issue](https://user-images.githubusercontent.com/66390685/84082544-a586e300-a9a5-11ea-9329-ca9254d9a12f.png)

![Sharedparameter Add issue_Revit](https://user-images.githubusercontent.com/66390685/84082559-a9b30080-a9a5-11ea-92ee-26d229020081.png)

[VDT_Shared Parameters_Driver.xlsx](https://github.com/erfajo/OrchidForDynamo/files/4748735/VDT_Shared.Parameters_Driver.xlsx)

[Shared Parameter Applicator - DYN.txt](https://github.com/erfajo/OrchidForDynamo/files/4748741/Shared.Parameter.Applicator.-.DYN.txt)

**Comment by erfajo** [comment]
please include the shared parameter files as well...

**Comment by sshatswell** [comment]
[VDT_Shared Parameters.txt](https://github.com/erfajo/OrchidForDynamo/files/4755210/VDT_Shared.Parameters.txt)

**Comment by erfajo** [comment]
hi @sshatswell 
since you are feeding the node with list values on all input, you need to tell the node that it must take them individually one by one. The nodes as such takes single input values on all input ports, except the parametername, which can take a list.
This means, that listlevel should be set as shown below.
![Shared Parameter Applicator](https://user-images.githubusercontent.com/2844374/84257099-244e5e00-ab15-11ea-9623-38dd7cd67ea2.png)

[Shared.Parameter.Applicator_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4757825/Shared.Parameter.Applicator_erfajo.dyn.txt)

**Comment by Toonblue** [comment]
Hi erfajo,
Like sshatswell, I have had the same problem using the SharedParameter.Add node. I have even installed your latest build but it is still giving me errors and not passing the shared parameters to the Revit family. Appreciate if you could give me some feedback. attached is screenshot and xls file.
regards
Toonblue
![shared param](https://user-images.githubusercontent.com/66796138/84421488-89887900-ac13-11ea-9063-405d00bb2482.png)
[AG-Shared Parameters June20.xlsx](https://github.com/erfajo/OrchidForDynamo/files/4766389/AG-Shared.Parameters.June20.xlsx)

**Comment by erfajo** [comment]
@Toonblue 
Try to add a watch node to the two output ports where you have added "yes"...

**Comment by Toonblue** [comment]
Hi erfajo,
I have changed in the code block the "Yes" to "Y" to match my spreadsheet and I get the expected results of false and true, but the node is still not pushing the parameters to the family.
However, the SharedParametre.Add node comes up with an error "Invalid Parameter Type". I went through my spreadsheet and yes there were errors as I had incorrect Built in parameter group names, e.g. PG_Identity data instead of PG_IDENTITY_DATA. I have checked everything in my spreadsheet but the script is still giving me errors. Any advice would be really appreciated.

![120620 SP add error](https://user-images.githubusercontent.com/66796138/84493732-30b2f200-aca0-11ea-8c40-3a5d41f79104.PNG)
[AG-HE SP.xlsx](https://github.com/erfajo/OrchidForDynamo/files/4770231/AG-HE.SP.xlsx)

**Comment by Toonblue** [comment]
forgot to mention I'm using Revit 2018, if that helps.

**Comment by erfajo** [comment]
well, add the bare minimum of all what I need to verify the graph, this includes, the graph file, the shared parameter file. I will use your added the excel file and I will take an empty family file, since nothing special is demanded. I will test it under RVT2018.

**Comment by Toonblue** [comment]
Thanks Erfajo, appreciate your help.
[AG-HE Shared Parameters Apr20.txt](https://github.com/erfajo/OrchidForDynamo/files/4771770/AG-HE.Shared.Parameters.Apr20.txt)


I can't add the graph file (.dyn) Can I email it to you, if so what is your email?

Regards

Ade
[AG-HE Shared Parameters Apr20.txt](https://github.com/erfajo/OrchidForDynamo/files/4771767/AG-HE.Shared.Parameters.Apr20.txt)

**Comment by erfajo** [comment]
do as @sshatswell did...

**Comment by Toonblue** [comment]
Hi erfajo
File as requested, many thanks

Ade
[Add shared paramBasic_dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4772394/Add.shared.paramBasic_dyn.txt)

**Comment by erfajo** [comment]
Finally I had some spare time to check you graph. The graph was exactly as it should be, you error is (as indicated in the error message) the wrong parameter type. In other words, the error is to be found in the excel file
![image](https://user-images.githubusercontent.com/2844374/85100565-b8e54a00-b200-11ea-8d51-ac69f96ec907.png)

**Comment by erfajo** [comment]
Since @sshatswell has not returned on his issue, which was the initial issue I will close this issue. If you @Toonblue still have errors please start a new issue.

**Comment by Toonblue** [comment]
Hi erfajo
Thanks for your reply. I have finally managed to get your node to work. So the parameter types are case sensitive. Cheers for your help.

**Comment by sshatswell** [comment]
Hey @erfajo 

Circling back to this - your level suggestion worked! Thank you! BTW, I found Orcid through AussieGuru. He's been a great resource for building Revit content, and a hand full of his tutorials use your custom nodes. Curiously, he used levels to manage data, but differently than you suggested - both with this application, and when opening a bunch of families in the background. 
Thanks again for your content and your engagement!
