### ISSUE TITLE
Orchid package for Revit 2021.1 and Dynamo 2.6?

### ISSUE THREAD

**Issue by jiridrahotusky** [erfajo/OrchidForDynamo#92]
Hi, 
maybe I found the right thread for my query ...
When will the Orchid package version for Revit 2021.1 Dynamo 2.6 be released?
Thanks
Jiri

**Comment by erfajo** [comment]
I will look into this asap, however, i am surprised that 2021.1 is released with dynamo 2.6... i will only release towards 2.6 if there is a Revit version supporting it. Besides is there no changes in the dynamo 2.5 og 2.6 version since there is no news in 2021.1 compared to 2021. It is primarily new things in Revit and the .net version the Revit version is using which is driving new major version numbers for me. All new nodes will be released supporting from Revit 2019 and up at the moment and first with 2022 will 2019 begin to be deprecated.

**Comment by jiridrahotusky** [comment]
The problem is that I have a number of Dynamo graphs that use Orchid nodes. Now, after installing the Revit update to version 2021.1 (Dynamo 2.6), I do not have the option to install the Orchid package and I do not have any of the nodes available. Orchid version 2.5 does not appear in Dynamo 2.6.
Wouldn't it be enough to recompile Orchid 2.5 to version 2.6 so far?

Here is link to image with version Dynamo 2.6:
https://kostka.adeon.cz:7001/sharing/ZUTNsdYz3

Jiri

**Comment by erfajo** [comment]
You can apply it by copying the Orchid folder from the 2.5 dynamo folder to the 2.6 dynamo folder, that should do it

**Comment by jiridrahotusky** [comment]
Oops, thanks. It didn't occur to me. I'll try it. Thanks for the reply.

**Comment by erfajo** [comment]
I have now released first build towards 2.6.1, but no code has changed. it is just a number replacement.
